items:
- uid: System.Runtime.Serialization.Json.DataContractJsonSerializerSettings
  href: System.Runtime.Serialization.Json.DataContractJsonSerializerSettings.yml
  name: DataContractJsonSerializerSettings
  fullName: System.Runtime.Serialization.Json.DataContractJsonSerializerSettings
  type: Class
  source:
    remote: &o0
      branch: master
      repo: https://github.com/dotnet/corefx.git
    path: src/System.Private.DataContractSerialization/src/System/Runtime/Serialization/Json/DataContractJsonSerializerSettings.cs
    startLine: 14
  summary: Dummy documentation
  syntax:
    content:
      CSharp: public class DataContractJsonSerializerSettings
  inheritance:
  - id: System.Object
    name: System.Object
    isExternal: true
  id: System.Runtime.Serialization.Json.DataContractJsonSerializerSettings
  children:
  - System.Runtime.Serialization.Json.DataContractJsonSerializerSettings.RootName
  - System.Runtime.Serialization.Json.DataContractJsonSerializerSettings.KnownTypes
  - System.Runtime.Serialization.Json.DataContractJsonSerializerSettings.MaxItemsInObjectGraph
  - System.Runtime.Serialization.Json.DataContractJsonSerializerSettings.IgnoreExtensionDataObject
  - System.Runtime.Serialization.Json.DataContractJsonSerializerSettings.EmitTypeInformation
  - System.Runtime.Serialization.Json.DataContractJsonSerializerSettings.DateTimeFormat
  - System.Runtime.Serialization.Json.DataContractJsonSerializerSettings.SerializeReadOnlyTypes
  - System.Runtime.Serialization.Json.DataContractJsonSerializerSettings.UseSimpleDictionaryFormat
- uid: System.Runtime.Serialization.Json.DataContractJsonSerializerSettings.RootName
  href: System.Runtime.Serialization.Json.DataContractJsonSerializerSettings.yml
  name: RootName
  fullName: System.Runtime.Serialization.Json.DataContractJsonSerializerSettings.RootName
  type: Property
  source:
    remote: *o0
    path: src/System.Private.DataContractSerialization/src/System/Runtime/Serialization/Json/DataContractJsonSerializerSettings.cs
    startLine: 21
  summary: Gets or sets Dummy documentation
  syntax:
    content:
      CSharp: public string RootName { get; set; }
    parameters:
    - id: RootName
      type:
        id: System.String
        name: System.String
        isExternal: true
  id: System.Runtime.Serialization.Json.DataContractJsonSerializerSettings.RootName
- uid: System.Runtime.Serialization.Json.DataContractJsonSerializerSettings.KnownTypes
  href: System.Runtime.Serialization.Json.DataContractJsonSerializerSettings.yml
  name: KnownTypes
  fullName: System.Runtime.Serialization.Json.DataContractJsonSerializerSettings.KnownTypes
  type: Property
  source:
    remote: *o0
    path: src/System.Private.DataContractSerialization/src/System/Runtime/Serialization/Json/DataContractJsonSerializerSettings.cs
    startLine: 26
  summary: Gets or sets Dummy documentation
  syntax:
    content:
      CSharp: public IEnumerable<Type> KnownTypes { get; set; }
    parameters:
    - id: KnownTypes
      type:
        id: IEnumerable{Type}
        name: IEnumerable{Type}
        isExternal: true
  id: System.Runtime.Serialization.Json.DataContractJsonSerializerSettings.KnownTypes
- uid: System.Runtime.Serialization.Json.DataContractJsonSerializerSettings.MaxItemsInObjectGraph
  href: System.Runtime.Serialization.Json.DataContractJsonSerializerSettings.yml
  name: MaxItemsInObjectGraph
  fullName: System.Runtime.Serialization.Json.DataContractJsonSerializerSettings.MaxItemsInObjectGraph
  type: Property
  source:
    remote: *o0
    path: src/System.Private.DataContractSerialization/src/System/Runtime/Serialization/Json/DataContractJsonSerializerSettings.cs
    startLine: 31
  summary: Gets or sets Dummy documentation
  syntax:
    content:
      CSharp: public int MaxItemsInObjectGraph { get; set; }
    parameters:
    - id: MaxItemsInObjectGraph
      type:
        id: System.Int32
        name: System.Int32
        isExternal: true
  id: System.Runtime.Serialization.Json.DataContractJsonSerializerSettings.MaxItemsInObjectGraph
- uid: System.Runtime.Serialization.Json.DataContractJsonSerializerSettings.IgnoreExtensionDataObject
  href: System.Runtime.Serialization.Json.DataContractJsonSerializerSettings.yml
  name: IgnoreExtensionDataObject
  fullName: System.Runtime.Serialization.Json.DataContractJsonSerializerSettings.IgnoreExtensionDataObject
  type: Property
  source:
    remote: *o0
    path: src/System.Private.DataContractSerialization/src/System/Runtime/Serialization/Json/DataContractJsonSerializerSettings.cs
    startLine: 47
  summary: Gets or sets a value indicating whether Dummy documentation
  syntax:
    content:
      CSharp: public bool IgnoreExtensionDataObject { get; set; }
    parameters:
    - id: IgnoreExtensionDataObject
      type:
        id: System.Boolean
        name: System.Boolean
        isExternal: true
  id: System.Runtime.Serialization.Json.DataContractJsonSerializerSettings.IgnoreExtensionDataObject
- uid: System.Runtime.Serialization.Json.DataContractJsonSerializerSettings.EmitTypeInformation
  href: System.Runtime.Serialization.Json.DataContractJsonSerializerSettings.yml
  name: EmitTypeInformation
  fullName: System.Runtime.Serialization.Json.DataContractJsonSerializerSettings.EmitTypeInformation
  type: Property
  source:
    remote: *o0
    path: src/System.Private.DataContractSerialization/src/System/Runtime/Serialization/Json/DataContractJsonSerializerSettings.cs
    startLine: 52
  summary: Gets or sets Dummy documentation
  syntax:
    content:
      CSharp: public EmitTypeInformation EmitTypeInformation { get; set; }
    parameters:
    - id: EmitTypeInformation
      type:
        id: System.Runtime.Serialization.EmitTypeInformation
        name: EmitTypeInformation
        href: System.Runtime.Serialization.EmitTypeInformation
  id: System.Runtime.Serialization.Json.DataContractJsonSerializerSettings.EmitTypeInformation
- uid: System.Runtime.Serialization.Json.DataContractJsonSerializerSettings.DateTimeFormat
  href: System.Runtime.Serialization.Json.DataContractJsonSerializerSettings.yml
  name: DateTimeFormat
  fullName: System.Runtime.Serialization.Json.DataContractJsonSerializerSettings.DateTimeFormat
  type: Property
  source:
    remote: *o0
    path: src/System.Private.DataContractSerialization/src/System/Runtime/Serialization/Json/DataContractJsonSerializerSettings.cs
    startLine: 57
  summary: Gets or sets Dummy documentation
  syntax:
    content:
      CSharp: public DateTimeFormat DateTimeFormat { get; set; }
    parameters:
    - id: DateTimeFormat
      type:
        id: System.Runtime.Serialization.DateTimeFormat
        name: DateTimeFormat
        href: System.Runtime.Serialization.DateTimeFormat
  id: System.Runtime.Serialization.Json.DataContractJsonSerializerSettings.DateTimeFormat
- uid: System.Runtime.Serialization.Json.DataContractJsonSerializerSettings.SerializeReadOnlyTypes
  href: System.Runtime.Serialization.Json.DataContractJsonSerializerSettings.yml
  name: SerializeReadOnlyTypes
  fullName: System.Runtime.Serialization.Json.DataContractJsonSerializerSettings.SerializeReadOnlyTypes
  type: Property
  source:
    remote: *o0
    path: src/System.Private.DataContractSerialization/src/System/Runtime/Serialization/Json/DataContractJsonSerializerSettings.cs
    startLine: 62
  summary: Gets or sets a value indicating whether Dummy documentation
  syntax:
    content:
      CSharp: public bool SerializeReadOnlyTypes { get; set; }
    parameters:
    - id: SerializeReadOnlyTypes
      type:
        id: System.Boolean
        name: System.Boolean
        isExternal: true
  id: System.Runtime.Serialization.Json.DataContractJsonSerializerSettings.SerializeReadOnlyTypes
- uid: System.Runtime.Serialization.Json.DataContractJsonSerializerSettings.UseSimpleDictionaryFormat
  href: System.Runtime.Serialization.Json.DataContractJsonSerializerSettings.yml
  name: UseSimpleDictionaryFormat
  fullName: System.Runtime.Serialization.Json.DataContractJsonSerializerSettings.UseSimpleDictionaryFormat
  type: Property
  source:
    remote: *o0
    path: src/System.Private.DataContractSerialization/src/System/Runtime/Serialization/Json/DataContractJsonSerializerSettings.cs
    startLine: 67
  summary: Gets or sets a value indicating whether Dummy documentation
  syntax:
    content:
      CSharp: public bool UseSimpleDictionaryFormat { get; set; }
    parameters:
    - id: UseSimpleDictionaryFormat
      type:
        id: System.Boolean
        name: System.Boolean
        isExternal: true
  id: System.Runtime.Serialization.Json.DataContractJsonSerializerSettings.UseSimpleDictionaryFormat
