items:
- uid: System.Security
  href: System.Security.yml
  name: Security
  fullName: System.Security
  type: Namespace
  source:
    remote:
      branch: master
      repo: https://github.com/dotnet/corefx.git
    path: src/System.Security.SecureString/src/System/Security/SecureStringMarshal.cs
    startLine: 5
  id: System.Security
  children:
  - System.Security.SecureString
  - System.Security.SecureStringMarshal
references:
- uid: System.Security.SecureString
  href: System.Security.SecureString.yml
  name: SecureString
  type: Class
- uid: System.Security.SecureStringMarshal
  href: System.Security.SecureStringMarshal.yml
  name: SecureStringMarshal
  type: Class
