items:
- uid: System.Security
  href: System.Security.yml
  name: Security
  fullName: System.Security
  type: Namespace
  source:
    remote:
      path: src/Microsoft.Win32.Registry/src/System/Security/AccessControl/RegistryRights.cs
      branch: master
      repo: https://github.com/dotnet/corefx.git
      key: 882a41e3
    path: src/Microsoft.Win32.Registry/src/System/Security/AccessControl/RegistryRights.cs
    startLine: 5
  id: System.Security
  children:
  - System.Security.SecureString
  - System.Security.SecureStringMarshal
references:
- uid: System.Security.SecureString
  href: System.Security.SecureString.yml
  name: SecureString
  type: Class
- uid: System.Security.SecureStringMarshal
  href: System.Security.SecureStringMarshal.yml
  name: SecureStringMarshal
  type: Class
