items:
- uid: System.Xml.XmlWriterSettings
  href: System.Xml.XmlWriterSettings.yml
  name: XmlWriterSettings
  fullName: System.Xml.XmlWriterSettings
  type: Class
  source:
    remote: &o0
      path: src/System.Xml.ReaderWriter/src/System/Xml/Core/XmlWriterSettings.cs
      branch: master
      repo: https://github.com/dotnet/corefx.git
      key: 882a41e3
    path: src/System.Xml.ReaderWriter/src/System/Xml/Core/XmlWriterSettings.cs
    startLine: 30
  syntax:
    content:
      CSharp: public sealed class XmlWriterSettings
  inheritance:
  - id: System.Object
    name: object
    isExternal: true
  id: System.Xml.XmlWriterSettings
  children:
  - System.Xml.XmlWriterSettings.#ctor
  - System.Xml.XmlWriterSettings.Async
  - System.Xml.XmlWriterSettings.Encoding
  - System.Xml.XmlWriterSettings.OmitXmlDeclaration
  - System.Xml.XmlWriterSettings.NewLineHandling
  - System.Xml.XmlWriterSettings.NewLineChars
  - System.Xml.XmlWriterSettings.Indent
  - System.Xml.XmlWriterSettings.IndentChars
  - System.Xml.XmlWriterSettings.NewLineOnAttributes
  - System.Xml.XmlWriterSettings.CloseOutput
  - System.Xml.XmlWriterSettings.ConformanceLevel
  - System.Xml.XmlWriterSettings.CheckCharacters
  - System.Xml.XmlWriterSettings.NamespaceHandling
  - System.Xml.XmlWriterSettings.WriteEndDocumentOnClose
  - System.Xml.XmlWriterSettings.Reset
  - System.Xml.XmlWriterSettings.Clone
- uid: System.Xml.XmlWriterSettings.#ctor
  href: System.Xml.XmlWriterSettings.yml
  name: XmlWriterSettings()
  fullName: System.Xml.XmlWriterSettings.XmlWriterSettings()
  type: Constructor
  source:
    remote: *o0
    path: src/System.Xml.ReaderWriter/src/System/Xml/Core/XmlWriterSettings.cs
    startLine: 66
  syntax:
    content:
      CSharp: public XmlWriterSettings()
    parameters: []
  id: System.Xml.XmlWriterSettings.#ctor
- uid: System.Xml.XmlWriterSettings.Async
  href: System.Xml.XmlWriterSettings.yml
  name: Async
  fullName: System.Xml.XmlWriterSettings.Async
  type: Property
  source:
    remote: *o0
    path: src/System.Xml.ReaderWriter/src/System/Xml/Core/XmlWriterSettings.cs
    startLine: 75
  syntax:
    content:
      CSharp: public bool Async { get; set; }
    parameters:
    - id: Async
      type:
        id: System.Boolean
        name: bool
        isExternal: true
  id: System.Xml.XmlWriterSettings.Async
- uid: System.Xml.XmlWriterSettings.Encoding
  href: System.Xml.XmlWriterSettings.yml
  name: Encoding
  fullName: System.Xml.XmlWriterSettings.Encoding
  type: Property
  source:
    remote: *o0
    path: src/System.Xml.ReaderWriter/src/System/Xml/Core/XmlWriterSettings.cs
    startLine: 89
  syntax:
    content:
      CSharp: public Encoding Encoding { get; set; }
    parameters:
    - id: Encoding
      type:
        id: System.Text.Encoding
        name: Encoding
        isExternal: true
  id: System.Xml.XmlWriterSettings.Encoding
- uid: System.Xml.XmlWriterSettings.OmitXmlDeclaration
  href: System.Xml.XmlWriterSettings.yml
  name: OmitXmlDeclaration
  fullName: System.Xml.XmlWriterSettings.OmitXmlDeclaration
  type: Property
  source:
    remote: *o0
    path: src/System.Xml.ReaderWriter/src/System/Xml/Core/XmlWriterSettings.cs
    startLine: 118
  syntax:
    content:
      CSharp: public bool OmitXmlDeclaration { get; set; }
    parameters:
    - id: OmitXmlDeclaration
      type:
        id: System.Boolean
        name: bool
        isExternal: true
  id: System.Xml.XmlWriterSettings.OmitXmlDeclaration
- uid: System.Xml.XmlWriterSettings.NewLineHandling
  href: System.Xml.XmlWriterSettings.yml
  name: NewLineHandling
  fullName: System.Xml.XmlWriterSettings.NewLineHandling
  type: Property
  source:
    remote: *o0
    path: src/System.Xml.ReaderWriter/src/System/Xml/Core/XmlWriterSettings.cs
    startLine: 132
  syntax:
    content:
      CSharp: public NewLineHandling NewLineHandling { get; set; }
    parameters:
    - id: NewLineHandling
      type:
        id: System.Xml.NewLineHandling
        name: NewLineHandling
        href: System.Xml.NewLineHandling.yml
  id: System.Xml.XmlWriterSettings.NewLineHandling
- uid: System.Xml.XmlWriterSettings.NewLineChars
  href: System.Xml.XmlWriterSettings.yml
  name: NewLineChars
  fullName: System.Xml.XmlWriterSettings.NewLineChars
  type: Property
  source:
    remote: *o0
    path: src/System.Xml.ReaderWriter/src/System/Xml/Core/XmlWriterSettings.cs
    startLine: 151
  syntax:
    content:
      CSharp: public string NewLineChars { get; set; }
    parameters:
    - id: NewLineChars
      type:
        id: System.String
        name: string
        isExternal: true
  id: System.Xml.XmlWriterSettings.NewLineChars
- uid: System.Xml.XmlWriterSettings.Indent
  href: System.Xml.XmlWriterSettings.yml
  name: Indent
  fullName: System.Xml.XmlWriterSettings.Indent
  type: Property
  source:
    remote: *o0
    path: src/System.Xml.ReaderWriter/src/System/Xml/Core/XmlWriterSettings.cs
    startLine: 170
  syntax:
    content:
      CSharp: public bool Indent { get; set; }
    parameters:
    - id: Indent
      type:
        id: System.Boolean
        name: bool
        isExternal: true
  id: System.Xml.XmlWriterSettings.Indent
- uid: System.Xml.XmlWriterSettings.IndentChars
  href: System.Xml.XmlWriterSettings.yml
  name: IndentChars
  fullName: System.Xml.XmlWriterSettings.IndentChars
  type: Property
  source:
    remote: *o0
    path: src/System.Xml.ReaderWriter/src/System/Xml/Core/XmlWriterSettings.cs
    startLine: 184
  syntax:
    content:
      CSharp: public string IndentChars { get; set; }
    parameters:
    - id: IndentChars
      type:
        id: System.String
        name: string
        isExternal: true
  id: System.Xml.XmlWriterSettings.IndentChars
- uid: System.Xml.XmlWriterSettings.NewLineOnAttributes
  href: System.Xml.XmlWriterSettings.yml
  name: NewLineOnAttributes
  fullName: System.Xml.XmlWriterSettings.NewLineOnAttributes
  type: Property
  source:
    remote: *o0
    path: src/System.Xml.ReaderWriter/src/System/Xml/Core/XmlWriterSettings.cs
    startLine: 203
  syntax:
    content:
      CSharp: public bool NewLineOnAttributes { get; set; }
    parameters:
    - id: NewLineOnAttributes
      type:
        id: System.Boolean
        name: bool
        isExternal: true
  id: System.Xml.XmlWriterSettings.NewLineOnAttributes
- uid: System.Xml.XmlWriterSettings.CloseOutput
  href: System.Xml.XmlWriterSettings.yml
  name: CloseOutput
  fullName: System.Xml.XmlWriterSettings.CloseOutput
  type: Property
  source:
    remote: *o0
    path: src/System.Xml.ReaderWriter/src/System/Xml/Core/XmlWriterSettings.cs
    startLine: 217
  syntax:
    content:
      CSharp: public bool CloseOutput { get; set; }
    parameters:
    - id: CloseOutput
      type:
        id: System.Boolean
        name: bool
        isExternal: true
  id: System.Xml.XmlWriterSettings.CloseOutput
- uid: System.Xml.XmlWriterSettings.ConformanceLevel
  href: System.Xml.XmlWriterSettings.yml
  name: ConformanceLevel
  fullName: System.Xml.XmlWriterSettings.ConformanceLevel
  type: Property
  source:
    remote: *o0
    path: src/System.Xml.ReaderWriter/src/System/Xml/Core/XmlWriterSettings.cs
    startLine: 233
  syntax:
    content:
      CSharp: public ConformanceLevel ConformanceLevel { get; set; }
    parameters:
    - id: ConformanceLevel
      type:
        id: System.Xml.ConformanceLevel
        name: ConformanceLevel
        href: System.Xml.ConformanceLevel.yml
  id: System.Xml.XmlWriterSettings.ConformanceLevel
- uid: System.Xml.XmlWriterSettings.CheckCharacters
  href: System.Xml.XmlWriterSettings.yml
  name: CheckCharacters
  fullName: System.Xml.XmlWriterSettings.CheckCharacters
  type: Property
  source:
    remote: *o0
    path: src/System.Xml.ReaderWriter/src/System/Xml/Core/XmlWriterSettings.cs
    startLine: 252
  syntax:
    content:
      CSharp: public bool CheckCharacters { get; set; }
    parameters:
    - id: CheckCharacters
      type:
        id: System.Boolean
        name: bool
        isExternal: true
  id: System.Xml.XmlWriterSettings.CheckCharacters
- uid: System.Xml.XmlWriterSettings.NamespaceHandling
  href: System.Xml.XmlWriterSettings.yml
  name: NamespaceHandling
  fullName: System.Xml.XmlWriterSettings.NamespaceHandling
  type: Property
  source:
    remote: *o0
    path: src/System.Xml.ReaderWriter/src/System/Xml/Core/XmlWriterSettings.cs
    startLine: 266
  syntax:
    content:
      CSharp: public NamespaceHandling NamespaceHandling { get; set; }
    parameters:
    - id: NamespaceHandling
      type:
        id: System.Xml.NamespaceHandling
        name: NamespaceHandling
        href: System.Xml.NamespaceHandling.yml
  id: System.Xml.XmlWriterSettings.NamespaceHandling
- uid: System.Xml.XmlWriterSettings.WriteEndDocumentOnClose
  href: System.Xml.XmlWriterSettings.yml
  name: WriteEndDocumentOnClose
  fullName: System.Xml.XmlWriterSettings.WriteEndDocumentOnClose
  type: Property
  source:
    remote: *o0
    path: src/System.Xml.ReaderWriter/src/System/Xml/Core/XmlWriterSettings.cs
    startLine: 284
  syntax:
    content:
      CSharp: public bool WriteEndDocumentOnClose { get; set; }
    parameters:
    - id: WriteEndDocumentOnClose
      type:
        id: System.Boolean
        name: bool
        isExternal: true
  id: System.Xml.XmlWriterSettings.WriteEndDocumentOnClose
- uid: System.Xml.XmlWriterSettings.Reset
  href: System.Xml.XmlWriterSettings.yml
  name: Reset()
  fullName: System.Xml.XmlWriterSettings.Reset()
  type: Method
  source:
    remote: *o0
    path: src/System.Xml.ReaderWriter/src/System/Xml/Core/XmlWriterSettings.cs
    startLine: 301
  syntax:
    content:
      CSharp: public void Reset()
    parameters: []
  id: System.Xml.XmlWriterSettings.Reset
- uid: System.Xml.XmlWriterSettings.Clone
  href: System.Xml.XmlWriterSettings.yml
  name: Clone()
  fullName: System.Xml.XmlWriterSettings.Clone()
  type: Method
  source:
    remote: *o0
    path: src/System.Xml.ReaderWriter/src/System/Xml/Core/XmlWriterSettings.cs
    startLine: 309
  syntax:
    content:
      CSharp: public XmlWriterSettings Clone()
    parameters: []
    return:
      id: XmlWriterSettings
      type:
        id: System.Xml.XmlWriterSettings
        name: XmlWriterSettings
        href: System.Xml.XmlWriterSettings.yml
  id: System.Xml.XmlWriterSettings.Clone
