id: System.Security
href: System.Security.yaml
name:
  CSharp: Security
qualifiedName:
  CSharp: System.Security
type: Namespace
source:
  remote:
    branch: master
    repo: https://github.com/dotnet/corefx.git
  path: src/System.Security.SecureString/src/System/Security/SecureStringMarshal.cs
  startLine: 5
items:
- id: System.Security.SecureString
  href: System.Security.SecureString.yaml
  type: Class
- id: System.Security.SecureStringMarshal
  href: System.Security.SecureStringMarshal.yaml
  type: Class
