items:
- uid: System.Xml.XmlReaderSettings
  href: System.Xml.XmlReaderSettings.yml
  name: XmlReaderSettings
  fullName: System.Xml.XmlReaderSettings
  type: Class
  source:
    remote: &o0
      path: src/System.Xml.ReaderWriter/src/System/Xml/Core/XmlReaderSettings.cs
      branch: master
      repo: https://github.com/dotnet/corefx.git
      key: 882a41e3
    path: src/System.Xml.ReaderWriter/src/System/Xml/Core/XmlReaderSettings.cs
    startLine: 10
  syntax:
    content:
      CSharp: public sealed class XmlReaderSettings
  inheritance:
  - id: System.Object
    name: object
    isExternal: true
  id: System.Xml.XmlReaderSettings
  children:
  - System.Xml.XmlReaderSettings.#ctor
  - System.Xml.XmlReaderSettings.Async
  - System.Xml.XmlReaderSettings.NameTable
  - System.Xml.XmlReaderSettings.LineNumberOffset
  - System.Xml.XmlReaderSettings.LinePositionOffset
  - System.Xml.XmlReaderSettings.ConformanceLevel
  - System.Xml.XmlReaderSettings.CheckCharacters
  - System.Xml.XmlReaderSettings.MaxCharactersInDocument
  - System.Xml.XmlReaderSettings.MaxCharactersFromEntities
  - System.Xml.XmlReaderSettings.IgnoreWhitespace
  - System.Xml.XmlReaderSettings.IgnoreProcessingInstructions
  - System.Xml.XmlReaderSettings.IgnoreComments
  - System.Xml.XmlReaderSettings.DtdProcessing
  - System.Xml.XmlReaderSettings.CloseInput
  - System.Xml.XmlReaderSettings.Reset
  - System.Xml.XmlReaderSettings.Clone
- uid: System.Xml.XmlReaderSettings.#ctor
  href: System.Xml.XmlReaderSettings.yml
  name: XmlReaderSettings()
  fullName: System.Xml.XmlReaderSettings.XmlReaderSettings()
  type: Constructor
  source:
    remote: *o0
    path: src/System.Xml.ReaderWriter/src/System/Xml/Core/XmlReaderSettings.cs
    startLine: 54
  syntax:
    content:
      CSharp: public XmlReaderSettings()
    parameters: []
  id: System.Xml.XmlReaderSettings.#ctor
- uid: System.Xml.XmlReaderSettings.Async
  href: System.Xml.XmlReaderSettings.yml
  name: Async
  fullName: System.Xml.XmlReaderSettings.Async
  type: Property
  source:
    remote: *o0
    path: src/System.Xml.ReaderWriter/src/System/Xml/Core/XmlReaderSettings.cs
    startLine: 63
  syntax:
    content:
      CSharp: public bool Async { get; set; }
    parameters:
    - id: Async
      type:
        id: System.Boolean
        name: bool
        isExternal: true
  id: System.Xml.XmlReaderSettings.Async
- uid: System.Xml.XmlReaderSettings.NameTable
  href: System.Xml.XmlReaderSettings.yml
  name: NameTable
  fullName: System.Xml.XmlReaderSettings.NameTable
  type: Property
  source:
    remote: *o0
    path: src/System.Xml.ReaderWriter/src/System/Xml/Core/XmlReaderSettings.cs
    startLine: 77
  syntax:
    content:
      CSharp: public XmlNameTable NameTable { get; set; }
    parameters:
    - id: NameTable
      type:
        id: System.Xml.XmlNameTable
        name: XmlNameTable
        href: System.Xml.XmlNameTable.yml
  id: System.Xml.XmlReaderSettings.NameTable
- uid: System.Xml.XmlReaderSettings.LineNumberOffset
  href: System.Xml.XmlReaderSettings.yml
  name: LineNumberOffset
  fullName: System.Xml.XmlReaderSettings.LineNumberOffset
  type: Property
  source:
    remote: *o0
    path: src/System.Xml.ReaderWriter/src/System/Xml/Core/XmlReaderSettings.cs
    startLine: 98
  syntax:
    content:
      CSharp: public int LineNumberOffset { get; set; }
    parameters:
    - id: LineNumberOffset
      type:
        id: System.Int32
        name: int
        isExternal: true
  id: System.Xml.XmlReaderSettings.LineNumberOffset
- uid: System.Xml.XmlReaderSettings.LinePositionOffset
  href: System.Xml.XmlReaderSettings.yml
  name: LinePositionOffset
  fullName: System.Xml.XmlReaderSettings.LinePositionOffset
  type: Property
  source:
    remote: *o0
    path: src/System.Xml.ReaderWriter/src/System/Xml/Core/XmlReaderSettings.cs
    startLine: 111
  syntax:
    content:
      CSharp: public int LinePositionOffset { get; set; }
    parameters:
    - id: LinePositionOffset
      type:
        id: System.Int32
        name: int
        isExternal: true
  id: System.Xml.XmlReaderSettings.LinePositionOffset
- uid: System.Xml.XmlReaderSettings.ConformanceLevel
  href: System.Xml.XmlReaderSettings.yml
  name: ConformanceLevel
  fullName: System.Xml.XmlReaderSettings.ConformanceLevel
  type: Property
  source:
    remote: *o0
    path: src/System.Xml.ReaderWriter/src/System/Xml/Core/XmlReaderSettings.cs
    startLine: 125
  syntax:
    content:
      CSharp: public ConformanceLevel ConformanceLevel { get; set; }
    parameters:
    - id: ConformanceLevel
      type:
        id: System.Xml.ConformanceLevel
        name: ConformanceLevel
        href: System.Xml.ConformanceLevel.yml
  id: System.Xml.XmlReaderSettings.ConformanceLevel
- uid: System.Xml.XmlReaderSettings.CheckCharacters
  href: System.Xml.XmlReaderSettings.yml
  name: CheckCharacters
  fullName: System.Xml.XmlReaderSettings.CheckCharacters
  type: Property
  source:
    remote: *o0
    path: src/System.Xml.ReaderWriter/src/System/Xml/Core/XmlReaderSettings.cs
    startLine: 143
  syntax:
    content:
      CSharp: public bool CheckCharacters { get; set; }
    parameters:
    - id: CheckCharacters
      type:
        id: System.Boolean
        name: bool
        isExternal: true
  id: System.Xml.XmlReaderSettings.CheckCharacters
- uid: System.Xml.XmlReaderSettings.MaxCharactersInDocument
  href: System.Xml.XmlReaderSettings.yml
  name: MaxCharactersInDocument
  fullName: System.Xml.XmlReaderSettings.MaxCharactersInDocument
  type: Property
  source:
    remote: *o0
    path: src/System.Xml.ReaderWriter/src/System/Xml/Core/XmlReaderSettings.cs
    startLine: 156
  syntax:
    content:
      CSharp: public long MaxCharactersInDocument { get; set; }
    parameters:
    - id: MaxCharactersInDocument
      type:
        id: System.Int64
        name: long
        isExternal: true
  id: System.Xml.XmlReaderSettings.MaxCharactersInDocument
- uid: System.Xml.XmlReaderSettings.MaxCharactersFromEntities
  href: System.Xml.XmlReaderSettings.yml
  name: MaxCharactersFromEntities
  fullName: System.Xml.XmlReaderSettings.MaxCharactersFromEntities
  type: Property
  source:
    remote: *o0
    path: src/System.Xml.ReaderWriter/src/System/Xml/Core/XmlReaderSettings.cs
    startLine: 173
  syntax:
    content:
      CSharp: public long MaxCharactersFromEntities { get; set; }
    parameters:
    - id: MaxCharactersFromEntities
      type:
        id: System.Int64
        name: long
        isExternal: true
  id: System.Xml.XmlReaderSettings.MaxCharactersFromEntities
- uid: System.Xml.XmlReaderSettings.IgnoreWhitespace
  href: System.Xml.XmlReaderSettings.yml
  name: IgnoreWhitespace
  fullName: System.Xml.XmlReaderSettings.IgnoreWhitespace
  type: Property
  source:
    remote: *o0
    path: src/System.Xml.ReaderWriter/src/System/Xml/Core/XmlReaderSettings.cs
    startLine: 191
  syntax:
    content:
      CSharp: public bool IgnoreWhitespace { get; set; }
    parameters:
    - id: IgnoreWhitespace
      type:
        id: System.Boolean
        name: bool
        isExternal: true
  id: System.Xml.XmlReaderSettings.IgnoreWhitespace
- uid: System.Xml.XmlReaderSettings.IgnoreProcessingInstructions
  href: System.Xml.XmlReaderSettings.yml
  name: IgnoreProcessingInstructions
  fullName: System.Xml.XmlReaderSettings.IgnoreProcessingInstructions
  type: Property
  source:
    remote: *o0
    path: src/System.Xml.ReaderWriter/src/System/Xml/Core/XmlReaderSettings.cs
    startLine: 204
  syntax:
    content:
      CSharp: public bool IgnoreProcessingInstructions { get; set; }
    parameters:
    - id: IgnoreProcessingInstructions
      type:
        id: System.Boolean
        name: bool
        isExternal: true
  id: System.Xml.XmlReaderSettings.IgnoreProcessingInstructions
- uid: System.Xml.XmlReaderSettings.IgnoreComments
  href: System.Xml.XmlReaderSettings.yml
  name: IgnoreComments
  fullName: System.Xml.XmlReaderSettings.IgnoreComments
  type: Property
  source:
    remote: *o0
    path: src/System.Xml.ReaderWriter/src/System/Xml/Core/XmlReaderSettings.cs
    startLine: 217
  syntax:
    content:
      CSharp: public bool IgnoreComments { get; set; }
    parameters:
    - id: IgnoreComments
      type:
        id: System.Boolean
        name: bool
        isExternal: true
  id: System.Xml.XmlReaderSettings.IgnoreComments
- uid: System.Xml.XmlReaderSettings.DtdProcessing
  href: System.Xml.XmlReaderSettings.yml
  name: DtdProcessing
  fullName: System.Xml.XmlReaderSettings.DtdProcessing
  type: Property
  source:
    remote: *o0
    path: src/System.Xml.ReaderWriter/src/System/Xml/Core/XmlReaderSettings.cs
    startLine: 231
  syntax:
    content:
      CSharp: public DtdProcessing DtdProcessing { get; set; }
    parameters:
    - id: DtdProcessing
      type:
        id: System.Xml.DtdProcessing
        name: DtdProcessing
        href: System.Xml.DtdProcessing.yml
  id: System.Xml.XmlReaderSettings.DtdProcessing
- uid: System.Xml.XmlReaderSettings.CloseInput
  href: System.Xml.XmlReaderSettings.yml
  name: CloseInput
  fullName: System.Xml.XmlReaderSettings.CloseInput
  type: Property
  source:
    remote: *o0
    path: src/System.Xml.ReaderWriter/src/System/Xml/Core/XmlReaderSettings.cs
    startLine: 249
  syntax:
    content:
      CSharp: public bool CloseInput { get; set; }
    parameters:
    - id: CloseInput
      type:
        id: System.Boolean
        name: bool
        isExternal: true
  id: System.Xml.XmlReaderSettings.CloseInput
- uid: System.Xml.XmlReaderSettings.Reset
  href: System.Xml.XmlReaderSettings.yml
  name: Reset()
  fullName: System.Xml.XmlReaderSettings.Reset()
  type: Method
  source:
    remote: *o0
    path: src/System.Xml.ReaderWriter/src/System/Xml/Core/XmlReaderSettings.cs
    startLine: 266
  syntax:
    content:
      CSharp: public void Reset()
    parameters: []
  id: System.Xml.XmlReaderSettings.Reset
- uid: System.Xml.XmlReaderSettings.Clone
  href: System.Xml.XmlReaderSettings.yml
  name: Clone()
  fullName: System.Xml.XmlReaderSettings.Clone()
  type: Method
  source:
    remote: *o0
    path: src/System.Xml.ReaderWriter/src/System/Xml/Core/XmlReaderSettings.cs
    startLine: 272
  syntax:
    content:
      CSharp: public XmlReaderSettings Clone()
    parameters: []
    return:
      id: XmlReaderSettings
      type:
        id: System.Xml.XmlReaderSettings
        name: XmlReaderSettings
        href: System.Xml.XmlReaderSettings.yml
  id: System.Xml.XmlReaderSettings.Clone
