items:
- uid: System.Runtime.Serialization.DataContractSerializerSettings
  href: System.Runtime.Serialization.DataContractSerializerSettings.yml
  name: DataContractSerializerSettings
  fullName: System.Runtime.Serialization.DataContractSerializerSettings
  type: Class
  source:
    remote: &o0
      path: src/System.Private.DataContractSerialization/src/System/Runtime/Serialization/DataContractSerializerSettings.cs
      branch: master
      repo: https://github.com/dotnet/corefx.git
      key: 882a41e3
    path: src/System.Private.DataContractSerialization/src/System/Runtime/Serialization/DataContractSerializerSettings.cs
    startLine: 14
  summary: Dummy documentation
  syntax:
    content:
      CSharp: public class DataContractSerializerSettings
  inheritance:
  - id: System.Object
    name: object
    isExternal: true
  id: System.Runtime.Serialization.DataContractSerializerSettings
  children:
  - System.Runtime.Serialization.DataContractSerializerSettings.RootName
  - System.Runtime.Serialization.DataContractSerializerSettings.RootNamespace
  - System.Runtime.Serialization.DataContractSerializerSettings.KnownTypes
  - System.Runtime.Serialization.DataContractSerializerSettings.MaxItemsInObjectGraph
  - System.Runtime.Serialization.DataContractSerializerSettings.PreserveObjectReferences
  - System.Runtime.Serialization.DataContractSerializerSettings.DataContractResolver
  - System.Runtime.Serialization.DataContractSerializerSettings.SerializeReadOnlyTypes
- uid: System.Runtime.Serialization.DataContractSerializerSettings.RootName
  href: System.Runtime.Serialization.DataContractSerializerSettings.yml
  name: RootName
  fullName: System.Runtime.Serialization.DataContractSerializerSettings.RootName
  type: Property
  source:
    remote: *o0
    path: src/System.Private.DataContractSerialization/src/System/Runtime/Serialization/DataContractSerializerSettings.cs
    startLine: 21
  summary: Gets or sets Dummy documentation
  syntax:
    content:
      CSharp: public XmlDictionaryString RootName { get; set; }
    parameters:
    - id: RootName
      type:
        id: System.Xml.XmlDictionaryString
        name: XmlDictionaryString
        href: System.Xml.XmlDictionaryString.yml
  id: System.Runtime.Serialization.DataContractSerializerSettings.RootName
- uid: System.Runtime.Serialization.DataContractSerializerSettings.RootNamespace
  href: System.Runtime.Serialization.DataContractSerializerSettings.yml
  name: RootNamespace
  fullName: System.Runtime.Serialization.DataContractSerializerSettings.RootNamespace
  type: Property
  source:
    remote: *o0
    path: src/System.Private.DataContractSerialization/src/System/Runtime/Serialization/DataContractSerializerSettings.cs
    startLine: 26
  summary: Gets or sets Dummy documentation
  syntax:
    content:
      CSharp: public XmlDictionaryString RootNamespace { get; set; }
    parameters:
    - id: RootNamespace
      type:
        id: System.Xml.XmlDictionaryString
        name: XmlDictionaryString
        href: System.Xml.XmlDictionaryString.yml
  id: System.Runtime.Serialization.DataContractSerializerSettings.RootNamespace
- uid: System.Runtime.Serialization.DataContractSerializerSettings.KnownTypes
  href: System.Runtime.Serialization.DataContractSerializerSettings.yml
  name: KnownTypes
  fullName: System.Runtime.Serialization.DataContractSerializerSettings.KnownTypes
  type: Property
  source:
    remote: *o0
    path: src/System.Private.DataContractSerialization/src/System/Runtime/Serialization/DataContractSerializerSettings.cs
    startLine: 31
  summary: Gets or sets Dummy documentation
  syntax:
    content:
      CSharp: public IEnumerable<Type> KnownTypes { get; set; }
    parameters:
    - id: KnownTypes
      type:
        id: System.Collections.Generic.IEnumerable{System.Type}
        name: IEnumerable<Type>
        isExternal: true
  id: System.Runtime.Serialization.DataContractSerializerSettings.KnownTypes
- uid: System.Runtime.Serialization.DataContractSerializerSettings.MaxItemsInObjectGraph
  href: System.Runtime.Serialization.DataContractSerializerSettings.yml
  name: MaxItemsInObjectGraph
  fullName: System.Runtime.Serialization.DataContractSerializerSettings.MaxItemsInObjectGraph
  type: Property
  source:
    remote: *o0
    path: src/System.Private.DataContractSerialization/src/System/Runtime/Serialization/DataContractSerializerSettings.cs
    startLine: 36
  summary: Gets or sets Dummy documentation
  syntax:
    content:
      CSharp: public int MaxItemsInObjectGraph { get; set; }
    parameters:
    - id: MaxItemsInObjectGraph
      type:
        id: System.Int32
        name: int
        isExternal: true
  id: System.Runtime.Serialization.DataContractSerializerSettings.MaxItemsInObjectGraph
- uid: System.Runtime.Serialization.DataContractSerializerSettings.PreserveObjectReferences
  href: System.Runtime.Serialization.DataContractSerializerSettings.yml
  name: PreserveObjectReferences
  fullName: System.Runtime.Serialization.DataContractSerializerSettings.PreserveObjectReferences
  type: Property
  source:
    remote: *o0
    path: src/System.Private.DataContractSerialization/src/System/Runtime/Serialization/DataContractSerializerSettings.cs
    startLine: 46
  summary: Gets or sets a value indicating whether Dummy documentation
  syntax:
    content:
      CSharp: public bool PreserveObjectReferences { get; set; }
    parameters:
    - id: PreserveObjectReferences
      type:
        id: System.Boolean
        name: bool
        isExternal: true
  id: System.Runtime.Serialization.DataContractSerializerSettings.PreserveObjectReferences
- uid: System.Runtime.Serialization.DataContractSerializerSettings.DataContractResolver
  href: System.Runtime.Serialization.DataContractSerializerSettings.yml
  name: DataContractResolver
  fullName: System.Runtime.Serialization.DataContractSerializerSettings.DataContractResolver
  type: Property
  source:
    remote: *o0
    path: src/System.Private.DataContractSerialization/src/System/Runtime/Serialization/DataContractSerializerSettings.cs
    startLine: 52
  summary: Gets or sets Dummy documentation
  syntax:
    content:
      CSharp: public DataContractResolver DataContractResolver { get; set; }
    parameters:
    - id: DataContractResolver
      type:
        id: System.Runtime.Serialization.DataContractResolver
        name: DataContractResolver
        href: System.Runtime.Serialization.DataContractResolver.yml
  id: System.Runtime.Serialization.DataContractSerializerSettings.DataContractResolver
- uid: System.Runtime.Serialization.DataContractSerializerSettings.SerializeReadOnlyTypes
  href: System.Runtime.Serialization.DataContractSerializerSettings.yml
  name: SerializeReadOnlyTypes
  fullName: System.Runtime.Serialization.DataContractSerializerSettings.SerializeReadOnlyTypes
  type: Property
  source:
    remote: *o0
    path: src/System.Private.DataContractSerialization/src/System/Runtime/Serialization/DataContractSerializerSettings.cs
    startLine: 57
  summary: Gets or sets a value indicating whether Dummy documentation
  syntax:
    content:
      CSharp: public bool SerializeReadOnlyTypes { get; set; }
    parameters:
    - id: SerializeReadOnlyTypes
      type:
        id: System.Boolean
        name: bool
        isExternal: true
  id: System.Runtime.Serialization.DataContractSerializerSettings.SerializeReadOnlyTypes
