items:
- uid: System.Web.Mvc.PreApplicationStartCode
  href: System.Web.Mvc.PreApplicationStartCode.yml
  name: PreApplicationStartCode
  fullName: System.Web.Mvc.PreApplicationStartCode
  type: Class
  source:
    remote: &o0
      path: src/System.Web.Mvc/PreApplicationStartCode.cs
      branch: master
      repo: https://git01.codeplex.com/aspnetwebstack
      key: 5fa60ca3
    path: src/System.Web.Mvc/PreApplicationStartCode.cs
    startLine: 7
  syntax:
    content:
      CSharp: public class PreApplicationStartCode
  inheritance:
  - id: System.Object
    name: object
    isExternal: true
  id: System.Web.Mvc.PreApplicationStartCode
  children:
  - System.Web.Mvc.PreApplicationStartCode.Start
- uid: System.Web.Mvc.PreApplicationStartCode.Start
  href: System.Web.Mvc.PreApplicationStartCode.yml
  name: Start()
  fullName: System.Web.Mvc.PreApplicationStartCode.Start()
  type: Method
  source:
    remote: *o0
    path: src/System.Web.Mvc/PreApplicationStartCode.cs
    startLine: 12
  syntax:
    content:
      CSharp: public static void Start()
    parameters: []
  id: System.Web.Mvc.PreApplicationStartCode.Start
