id: System.Web.Mvc.PreApplicationStartCode
href: System.Web.Mvc.PreApplicationStartCode.yaml
name:
  CSharp: PreApplicationStartCode
qualifiedName:
  CSharp: System.Web.Mvc.PreApplicationStartCode
type: Class
source:
  remote: &o0
    branch: master
    repo: https://git01.codeplex.com/aspnetwebstack
    description: fbv1.1-beta-39-g5fa60ca
  path: src/System.Web.Mvc/PreApplicationStartCode.cs
  startLine: 7
syntax:
  content:
    CSharp: public static class PreApplicationStartCode
inheritance:
- id: System.Object
  name: System.Object
  isExternal: true
items:
- id: System.Web.Mvc.PreApplicationStartCode.Start
  href: System.Web.Mvc.PreApplicationStartCode.yaml
  name:
    CSharp: Start
  qualifiedName:
    CSharp: System.Web.Mvc.PreApplicationStartCode.Start
  type: Method
  source:
    remote: *o0
    path: src/System.Web.Mvc/PreApplicationStartCode.cs
    startLine: 12
  syntax:
    content:
      CSharp: public static void Start()
    parameters: []
    return:
      id: Void
