items:
- uid: ImageProcessor.Web.Configuration.ImageSecuritySection.ServiceElement
  href: ImageProcessor.Web.Configuration.ImageSecuritySection.ServiceElement.yml
  name: ServiceElement
  fullName: ImageProcessor.Web.Configuration.ImageSecuritySection.ServiceElement
  type: Class
  source:
    remote: &o0
      path: src/ImageProcessor.Web/Configuration/ImageSecuritySection.cs
      branch: V2
      repo: https://github.com/JimBobSquarePants/ImageProcessor.git
      key: 6d1ac546
    path: src/ImageProcessor.Web/Configuration/ImageSecuritySection.cs
    startLine: 82
  summary: Represents a ServiceElement configuration element within the configuration.
  syntax:
    content:
      CSharp: 'public class ServiceElement : ConfigurationElement'
  inheritance:
  - id: System.Object
    name: object
    isExternal: true
  - id: System.Configuration.ConfigurationElement
    name: ConfigurationElement
    isExternal: true
  id: ImageProcessor.Web.Configuration.ImageSecuritySection.ServiceElement
  children:
  - ImageProcessor.Web.Configuration.ImageSecuritySection.ServiceElement.Name
  - ImageProcessor.Web.Configuration.ImageSecuritySection.ServiceElement.Prefix
  - ImageProcessor.Web.Configuration.ImageSecuritySection.ServiceElement.Type
  - ImageProcessor.Web.Configuration.ImageSecuritySection.ServiceElement.Settings
  - ImageProcessor.Web.Configuration.ImageSecuritySection.ServiceElement.WhiteList
- uid: ImageProcessor.Web.Configuration.ImageSecuritySection.ServiceElement.Name
  href: ImageProcessor.Web.Configuration.ImageSecuritySection.ServiceElement.yml
  name: Name
  fullName: ImageProcessor.Web.Configuration.ImageSecuritySection.ServiceElement.Name
  type: Property
  source:
    remote: *o0
    path: src/ImageProcessor.Web/Configuration/ImageSecuritySection.cs
    startLine: 88
  summary: Gets or sets the name of the service.
  syntax:
    content:
      CSharp: '[ConfigurationProperty("name", DefaultValue = "", IsRequired = true)] public string Name { get; set; }'
    parameters:
    - id: Name
      type:
        id: System.String
        name: string
        isExternal: true
  id: ImageProcessor.Web.Configuration.ImageSecuritySection.ServiceElement.Name
- uid: ImageProcessor.Web.Configuration.ImageSecuritySection.ServiceElement.Prefix
  href: ImageProcessor.Web.Configuration.ImageSecuritySection.ServiceElement.yml
  name: Prefix
  fullName: ImageProcessor.Web.Configuration.ImageSecuritySection.ServiceElement.Prefix
  type: Property
  source:
    remote: *o0
    path: src/ImageProcessor.Web/Configuration/ImageSecuritySection.cs
    startLine: 100
  summary: Gets or sets the prefix of the service.
  syntax:
    content:
      CSharp: '[ConfigurationProperty("prefix", DefaultValue = "", IsRequired = false)] public string Prefix { get; set; }'
    parameters:
    - id: Prefix
      type:
        id: System.String
        name: string
        isExternal: true
  id: ImageProcessor.Web.Configuration.ImageSecuritySection.ServiceElement.Prefix
- uid: ImageProcessor.Web.Configuration.ImageSecuritySection.ServiceElement.Type
  href: ImageProcessor.Web.Configuration.ImageSecuritySection.ServiceElement.yml
  name: Type
  fullName: ImageProcessor.Web.Configuration.ImageSecuritySection.ServiceElement.Type
  type: Property
  source:
    remote: *o0
    path: src/ImageProcessor.Web/Configuration/ImageSecuritySection.cs
    startLine: 112
  summary: Gets or sets the type of the service.
  syntax:
    content:
      CSharp: '[ConfigurationProperty("type", DefaultValue = "", IsRequired = true)] public string Type { get; set; }'
    parameters:
    - id: Type
      type:
        id: System.String
        name: string
        isExternal: true
  id: ImageProcessor.Web.Configuration.ImageSecuritySection.ServiceElement.Type
- uid: ImageProcessor.Web.Configuration.ImageSecuritySection.ServiceElement.Settings
  href: ImageProcessor.Web.Configuration.ImageSecuritySection.ServiceElement.yml
  name: Settings
  fullName: ImageProcessor.Web.Configuration.ImageSecuritySection.ServiceElement.Settings
  type: Property
  source:
    remote: *o0
    path: src/ImageProcessor.Web/Configuration/ImageSecuritySection.cs
    startLine: 126
  summary: Gets the [ImageProcessor.Web.Configuration.SettingElementCollection](api/ImageProcessor.Web.Configuration.SettingElementCollection.yml).
  syntax:
    content:
      CSharp: '[ConfigurationProperty("settings", IsRequired = false)] public SettingElementCollection Settings { get; }'
    parameters:
    - id: Settings
      type:
        id: ImageProcessor.Web.Configuration.SettingElementCollection
        name: SettingElementCollection
        href: ImageProcessor.Web.Configuration.SettingElementCollection.yml
  id: ImageProcessor.Web.Configuration.ImageSecuritySection.ServiceElement.Settings
- uid: ImageProcessor.Web.Configuration.ImageSecuritySection.ServiceElement.WhiteList
  href: ImageProcessor.Web.Configuration.ImageSecuritySection.ServiceElement.yml
  name: WhiteList
  fullName: ImageProcessor.Web.Configuration.ImageSecuritySection.ServiceElement.WhiteList
  type: Property
  source:
    remote: *o0
    path: src/ImageProcessor.Web/Configuration/ImageSecuritySection.cs
    startLine: 141
  summary: Gets the [ImageProcessor.Web.Config.ImageSecuritySection.WhiteListElementCollection](#).
  syntax:
    content:
      CSharp: '[ConfigurationProperty("whitelist", IsRequired = false)] public WhiteListElementCollection WhiteList { get; }'
    parameters:
    - id: WhiteList
      type:
        id: ImageProcessor.Web.Configuration.ImageSecuritySection.WhiteListElementCollection
        name: WhiteListElementCollection
        href: ImageProcessor.Web.Configuration.ImageSecuritySection.WhiteListElementCollection.yml
  id: ImageProcessor.Web.Configuration.ImageSecuritySection.ServiceElement.WhiteList
