items:
- uid: ImageProcessor.Web.Configuration.ImageCacheSection.CacheElement
  href: ImageProcessor.Web.Configuration.ImageCacheSection.CacheElement.yml
  name: CacheElement
  fullName: ImageProcessor.Web.Configuration.ImageCacheSection.CacheElement
  type: Class
  source:
    remote: &o0
      path: src/ImageProcessor.Web/Configuration/ImageCacheSection.cs
      branch: V2
      repo: https://github.com/JimBobSquarePants/ImageProcessor.git
      key: 6d1ac546
    path: src/ImageProcessor.Web/Configuration/ImageCacheSection.cs
    startLine: 79
  summary: Represents a CacheElement configuration element within the configuration.
  syntax:
    content:
      CSharp: 'public class CacheElement : ConfigurationElement'
  inheritance:
  - id: System.Object
    name: object
    isExternal: true
  - id: System.Configuration.ConfigurationElement
    name: ConfigurationElement
    isExternal: true
  id: ImageProcessor.Web.Configuration.ImageCacheSection.CacheElement
  children:
  - ImageProcessor.Web.Configuration.ImageCacheSection.CacheElement.Name
  - ImageProcessor.Web.Configuration.ImageCacheSection.CacheElement.Type
  - ImageProcessor.Web.Configuration.ImageCacheSection.CacheElement.MaxDays
  - ImageProcessor.Web.Configuration.ImageCacheSection.CacheElement.Settings
- uid: ImageProcessor.Web.Configuration.ImageCacheSection.CacheElement.Name
  href: ImageProcessor.Web.Configuration.ImageCacheSection.CacheElement.yml
  name: Name
  fullName: ImageProcessor.Web.Configuration.ImageCacheSection.CacheElement.Name
  type: Property
  source:
    remote: *o0
    path: src/ImageProcessor.Web/Configuration/ImageCacheSection.cs
    startLine: 85
  summary: Gets or sets the name of the cache.
  syntax:
    content:
      CSharp: '[ConfigurationProperty("name", DefaultValue = "", IsRequired = true)] public string Name { get; set; }'
    parameters:
    - id: Name
      type:
        id: System.String
        name: string
        isExternal: true
  id: ImageProcessor.Web.Configuration.ImageCacheSection.CacheElement.Name
- uid: ImageProcessor.Web.Configuration.ImageCacheSection.CacheElement.Type
  href: ImageProcessor.Web.Configuration.ImageCacheSection.CacheElement.yml
  name: Type
  fullName: ImageProcessor.Web.Configuration.ImageCacheSection.CacheElement.Type
  type: Property
  source:
    remote: *o0
    path: src/ImageProcessor.Web/Configuration/ImageCacheSection.cs
    startLine: 97
  summary: Gets or sets the type of the cache.
  syntax:
    content:
      CSharp: '[ConfigurationProperty("type", DefaultValue = "", IsRequired = true)] public string Type { get; set; }'
    parameters:
    - id: Type
      type:
        id: System.String
        name: string
        isExternal: true
  id: ImageProcessor.Web.Configuration.ImageCacheSection.CacheElement.Type
- uid: ImageProcessor.Web.Configuration.ImageCacheSection.CacheElement.MaxDays
  href: ImageProcessor.Web.Configuration.ImageCacheSection.CacheElement.yml
  name: MaxDays
  fullName: ImageProcessor.Web.Configuration.ImageCacheSection.CacheElement.MaxDays
  type: Property
  source:
    remote: *o0
    path: src/ImageProcessor.Web/Configuration/ImageCacheSection.cs
    startLine: 110
  summary: Gets or sets the maximum number of days to store an image in the cache.
  syntax:
    content:
      CSharp: '[ConfigurationProperty("maxDays", DefaultValue = "365", IsRequired = true)] [IntegerValidator(ExcludeRange = false, MinValue = 0)] public int MaxDays { get; set; }'
    parameters:
    - id: MaxDays
      type:
        id: System.Int32
        name: int
        isExternal: true
  id: ImageProcessor.Web.Configuration.ImageCacheSection.CacheElement.MaxDays
- uid: ImageProcessor.Web.Configuration.ImageCacheSection.CacheElement.Settings
  href: ImageProcessor.Web.Configuration.ImageCacheSection.CacheElement.yml
  name: Settings
  fullName: ImageProcessor.Web.Configuration.ImageCacheSection.CacheElement.Settings
  type: Property
  source:
    remote: *o0
    path: src/ImageProcessor.Web/Configuration/ImageCacheSection.cs
    startLine: 131
  summary: Gets the [ImageProcessor.Web.Configuration.SettingElementCollection](api/ImageProcessor.Web.Configuration.SettingElementCollection.yml).
  syntax:
    content:
      CSharp: '[ConfigurationProperty("settings", IsRequired = false)] public SettingElementCollection Settings { get; }'
    parameters:
    - id: Settings
      type:
        id: ImageProcessor.Web.Configuration.SettingElementCollection
        name: SettingElementCollection
        href: ImageProcessor.Web.Configuration.SettingElementCollection.yml
  id: ImageProcessor.Web.Configuration.ImageCacheSection.CacheElement.Settings
