items:
- uid: ImageProcessor.Web.Configuration.ImageSecuritySection.ServiceElementCollection
  href: ImageProcessor.Web.Configuration.ImageSecuritySection.ServiceElementCollection.yml
  name: ServiceElementCollection
  fullName: ImageProcessor.Web.Configuration.ImageSecuritySection.ServiceElementCollection
  type: Class
  source:
    remote: &o0
      path: src/ImageProcessor.Web/Configuration/ImageSecuritySection.cs
      branch: V2
      repo: https://github.com/JimBobSquarePants/ImageProcessor.git
      key: 6d1ac546
    path: src/ImageProcessor.Web/Configuration/ImageSecuritySection.cs
    startLine: 154
  summary: Represents a collection of [ImageProcessor.Web.Configuration.ImageSecuritySection.ServiceElement](api/ImageProcessor.Web.Configuration.ImageSecuritySection.ServiceElement.yml) elements within the configuration.
  syntax:
    content:
      CSharp: 'public class ServiceElementCollection : ConfigurationElementCollection, ICollection, IEnumerable'
  inheritance:
  - id: System.Object
    name: object
    isExternal: true
  - id: System.Configuration.ConfigurationElement
    name: ConfigurationElement
    isExternal: true
  - id: System.Configuration.ConfigurationElementCollection
    name: ConfigurationElementCollection
    isExternal: true
  id: ImageProcessor.Web.Configuration.ImageSecuritySection.ServiceElementCollection
  children:
  - ImageProcessor.Web.Configuration.ImageSecuritySection.ServiceElementCollection.CollectionType
  - ImageProcessor.Web.Configuration.ImageSecuritySection.ServiceElementCollection.ElementName
  - ImageProcessor.Web.Configuration.ImageSecuritySection.ServiceElementCollection.Item(System.Int32)
  - ImageProcessor.Web.Configuration.ImageSecuritySection.ServiceElementCollection.CreateNewElement
  - ImageProcessor.Web.Configuration.ImageSecuritySection.ServiceElementCollection.GetElementKey(System.Configuration.ConfigurationElement)
- uid: ImageProcessor.Web.Configuration.ImageSecuritySection.ServiceElementCollection.CollectionType
  href: ImageProcessor.Web.Configuration.ImageSecuritySection.ServiceElementCollection.yml
  name: CollectionType
  fullName: ImageProcessor.Web.Configuration.ImageSecuritySection.ServiceElementCollection.CollectionType
  type: Property
  source:
    remote: *o0
    path: src/ImageProcessor.Web/Configuration/ImageSecuritySection.cs
    startLine: 162
  summary: Gets the type of the [System.Configuration.ConfigurationElementCollection](#).
  syntax:
    content:
      CSharp: public override ConfigurationElementCollectionType CollectionType { get; }
    parameters:
    - id: CollectionType
      type:
        id: System.Configuration.ConfigurationElementCollectionType
        name: ConfigurationElementCollectionType
        isExternal: true
  id: ImageProcessor.Web.Configuration.ImageSecuritySection.ServiceElementCollection.CollectionType
- uid: ImageProcessor.Web.Configuration.ImageSecuritySection.ServiceElementCollection.ElementName
  href: ImageProcessor.Web.Configuration.ImageSecuritySection.ServiceElementCollection.yml
  name: ElementName
  fullName: ImageProcessor.Web.Configuration.ImageSecuritySection.ServiceElementCollection.ElementName
  type: Property
  source:
    remote: *o0
    path: src/ImageProcessor.Web/Configuration/ImageSecuritySection.cs
    startLine: 173
  summary: Gets the name used to identify this collection of elements in the configuration file when overridden in a derived class.
  syntax:
    content:
      CSharp: protected override string ElementName { get; }
    parameters:
    - id: ElementName
      type:
        id: System.String
        name: string
        isExternal: true
  id: ImageProcessor.Web.Configuration.ImageSecuritySection.ServiceElementCollection.ElementName
- uid: ImageProcessor.Web.Configuration.ImageSecuritySection.ServiceElementCollection.Item(System.Int32)
  href: ImageProcessor.Web.Configuration.ImageSecuritySection.ServiceElementCollection.yml
  name: this[int]
  fullName: ImageProcessor.Web.Configuration.ImageSecuritySection.ServiceElementCollection.this[int]
  type: Property
  source:
    remote: *o0
    path: src/ImageProcessor.Web/Configuration/ImageSecuritySection.cs
    startLine: 187
  summary: >-
    Gets or sets the [ImageProcessor.Web.Config.ImageSecuritySection.ServiceElement](#)

    at the specified index within the collection.
  syntax:
    content:
      CSharp: public ServiceElement this[int index] { get; set; }
    parameters:
    - id: this[]
      type:
        id: ImageProcessor.Web.Configuration.ImageSecuritySection.ServiceElement
        name: ServiceElement
        href: ImageProcessor.Web.Configuration.ImageSecuritySection.ServiceElement.yml
  id: ImageProcessor.Web.Configuration.ImageSecuritySection.ServiceElementCollection.Item(System.Int32)
- uid: ImageProcessor.Web.Configuration.ImageSecuritySection.ServiceElementCollection.CreateNewElement
  href: ImageProcessor.Web.Configuration.ImageSecuritySection.ServiceElementCollection.yml
  name: CreateNewElement()
  fullName: ImageProcessor.Web.Configuration.ImageSecuritySection.ServiceElementCollection.CreateNewElement()
  type: Method
  source:
    remote: *o0
    path: src/ImageProcessor.Web/Configuration/ImageSecuritySection.cs
    startLine: 211
  summary: When overridden in a derived class, creates a new [System.Configuration.ConfigurationElement](#).
  syntax:
    content:
      CSharp: protected override ConfigurationElement CreateNewElement()
    parameters: []
    return:
      id: ConfigurationElement
      type:
        id: System.Configuration.ConfigurationElement
        name: ConfigurationElement
        isExternal: true
      description: A new [System.Configuration.ConfigurationElement](#).
  id: ImageProcessor.Web.Configuration.ImageSecuritySection.ServiceElementCollection.CreateNewElement
- uid: ImageProcessor.Web.Configuration.ImageSecuritySection.ServiceElementCollection.GetElementKey(System.Configuration.ConfigurationElement)
  href: ImageProcessor.Web.Configuration.ImageSecuritySection.ServiceElementCollection.yml
  name: GetElementKey(ConfigurationElement)
  fullName: ImageProcessor.Web.Configuration.ImageSecuritySection.ServiceElementCollection.GetElementKey(System.Configuration.ConfigurationElement)
  type: Method
  source:
    remote: *o0
    path: src/ImageProcessor.Web/Configuration/ImageSecuritySection.cs
    startLine: 223
  summary: Gets the element key for a specified configuration element when overridden in a derived class.
  syntax:
    content:
      CSharp: protected override object GetElementKey(ConfigurationElement element)
    parameters:
    - id: element
      type:
        id: System.Configuration.ConfigurationElement
        name: ConfigurationElement
        isExternal: true
      description: The [System.Configuration.ConfigurationElement](#) to return the key for.
    return:
      id: Object
      type:
        id: System.Object
        name: object
        isExternal: true
      description: An [System.Object](#) that acts as the key for the specified [System.Configuration.ConfigurationElement](#).
  id: ImageProcessor.Web.Configuration.ImageSecuritySection.ServiceElementCollection.GetElementKey(System.Configuration.ConfigurationElement)
