items:
- uid: ImageProcessor.Web.Configuration.SettingElementCollection
  href: ImageProcessor.Web.Configuration.SettingElementCollection.yml
  name: SettingElementCollection
  fullName: ImageProcessor.Web.Configuration.SettingElementCollection
  type: Class
  source:
    remote: &o0
      path: src/ImageProcessor.Web/Configuration/Shared/SettingElementCollection.cs
      branch: V2
      repo: https://github.com/JimBobSquarePants/ImageProcessor.git
      key: 6d1ac546
    path: src/ImageProcessor.Web/Configuration/Shared/SettingElementCollection.cs
    startLine: 18
  summary: Represents a SettingElementCollection collection configuration element within the configuration.
  syntax:
    content:
      CSharp: 'public class SettingElementCollection : ConfigurationElementCollection, ICollection, IEnumerable'
  inheritance:
  - id: System.Object
    name: object
    isExternal: true
  - id: System.Configuration.ConfigurationElement
    name: ConfigurationElement
    isExternal: true
  - id: System.Configuration.ConfigurationElementCollection
    name: ConfigurationElementCollection
    isExternal: true
  id: ImageProcessor.Web.Configuration.SettingElementCollection
  children:
  - ImageProcessor.Web.Configuration.SettingElementCollection.CollectionType
  - ImageProcessor.Web.Configuration.SettingElementCollection.ElementName
  - ImageProcessor.Web.Configuration.SettingElementCollection.Item(System.Int32)
  - ImageProcessor.Web.Configuration.SettingElementCollection.Item(System.String)
  - ImageProcessor.Web.Configuration.SettingElementCollection.ContainsKey(System.String)
  - ImageProcessor.Web.Configuration.SettingElementCollection.GetElementKey(System.Configuration.ConfigurationElement)
  - ImageProcessor.Web.Configuration.SettingElementCollection.CreateNewElement
- uid: ImageProcessor.Web.Configuration.SettingElementCollection.CollectionType
  href: ImageProcessor.Web.Configuration.SettingElementCollection.yml
  name: CollectionType
  fullName: ImageProcessor.Web.Configuration.SettingElementCollection.CollectionType
  type: Property
  source:
    remote: *o0
    path: src/ImageProcessor.Web/Configuration/Shared/SettingElementCollection.cs
    startLine: 26
  summary: Gets the type of the [System.Configuration.ConfigurationElementCollection](#).
  syntax:
    content:
      CSharp: public override ConfigurationElementCollectionType CollectionType { get; }
    parameters:
    - id: CollectionType
      type:
        id: System.Configuration.ConfigurationElementCollectionType
        name: ConfigurationElementCollectionType
        isExternal: true
  id: ImageProcessor.Web.Configuration.SettingElementCollection.CollectionType
- uid: ImageProcessor.Web.Configuration.SettingElementCollection.ElementName
  href: ImageProcessor.Web.Configuration.SettingElementCollection.yml
  name: ElementName
  fullName: ImageProcessor.Web.Configuration.SettingElementCollection.ElementName
  type: Property
  source:
    remote: *o0
    path: src/ImageProcessor.Web/Configuration/Shared/SettingElementCollection.cs
    startLine: 37
  summary: Gets the name used to identify this collection of elements in the configuration file when overridden in a derived class.
  syntax:
    content:
      CSharp: protected override string ElementName { get; }
    parameters:
    - id: ElementName
      type:
        id: System.String
        name: string
        isExternal: true
  id: ImageProcessor.Web.Configuration.SettingElementCollection.ElementName
- uid: ImageProcessor.Web.Configuration.SettingElementCollection.Item(System.Int32)
  href: ImageProcessor.Web.Configuration.SettingElementCollection.yml
  name: this[int]
  fullName: ImageProcessor.Web.Configuration.SettingElementCollection.this[int]
  type: Property
  source:
    remote: *o0
    path: src/ImageProcessor.Web/Configuration/Shared/SettingElementCollection.cs
    startLine: 51
  summary: >-
    Gets or sets the [ImageProcessor.Web.Config.ImageSecuritySection.SettingElement](#)

    at the specified index within the collection.
  syntax:
    content:
      CSharp: public SettingElement this[int index] { get; set; }
    parameters:
    - id: this[]
      type:
        id: ImageProcessor.Web.Configuration.SettingElement
        name: SettingElement
        href: ImageProcessor.Web.Configuration.SettingElement.yml
  id: ImageProcessor.Web.Configuration.SettingElementCollection.Item(System.Int32)
- uid: ImageProcessor.Web.Configuration.SettingElementCollection.Item(System.String)
  href: ImageProcessor.Web.Configuration.SettingElementCollection.yml
  name: this[string]
  fullName: ImageProcessor.Web.Configuration.SettingElementCollection.this[string]
  type: Property
  source:
    remote: *o0
    path: src/ImageProcessor.Web/Configuration/Shared/SettingElementCollection.cs
    startLine: 74
  summary: Returns the setting element with the specified key.
  syntax:
    content:
      CSharp: public new SettingElement this[string key] { get; }
    parameters:
    - id: this[]
      type:
        id: ImageProcessor.Web.Configuration.SettingElement
        name: SettingElement
        href: ImageProcessor.Web.Configuration.SettingElement.yml
  id: ImageProcessor.Web.Configuration.SettingElementCollection.Item(System.String)
- uid: ImageProcessor.Web.Configuration.SettingElementCollection.ContainsKey(System.String)
  href: ImageProcessor.Web.Configuration.SettingElementCollection.yml
  name: ContainsKey(string)
  fullName: ImageProcessor.Web.Configuration.SettingElementCollection.ContainsKey(string)
  type: Method
  source:
    remote: *o0
    path: src/ImageProcessor.Web/Configuration/Shared/SettingElementCollection.cs
    startLine: 85
  summary: >-
    Returns a value indicating whether the settings collection contains the

    given object.
  syntax:
    content:
      CSharp: public bool ContainsKey(string key)
    parameters:
    - id: key
      type:
        id: System.String
        name: string
        isExternal: true
      description: The key to identify the setting.
    return:
      id: Boolean
      type:
        id: System.Boolean
        name: bool
        isExternal: true
      description: True if the collection contains the key; otherwise false.
  id: ImageProcessor.Web.Configuration.SettingElementCollection.ContainsKey(System.String)
- uid: ImageProcessor.Web.Configuration.SettingElementCollection.GetElementKey(System.Configuration.ConfigurationElement)
  href: ImageProcessor.Web.Configuration.SettingElementCollection.yml
  name: GetElementKey(ConfigurationElement)
  fullName: ImageProcessor.Web.Configuration.SettingElementCollection.GetElementKey(System.Configuration.ConfigurationElement)
  type: Method
  source:
    remote: *o0
    path: src/ImageProcessor.Web/Configuration/Shared/SettingElementCollection.cs
    startLine: 100
  summary: Gets the element key for a specified PluginElement configuration element.
  syntax:
    content:
      CSharp: protected override object GetElementKey(ConfigurationElement element)
    parameters:
    - id: element
      type:
        id: System.Configuration.ConfigurationElement
        name: ConfigurationElement
        isExternal: true
      description: >-
        The [System.Configuration.ConfigurationElement](#)

        to return the key for.
    return:
      id: Object
      type:
        id: System.Object
        name: object
        isExternal: true
      description: The element key for a specified PluginElement configuration element.
  id: ImageProcessor.Web.Configuration.SettingElementCollection.GetElementKey(System.Configuration.ConfigurationElement)
- uid: ImageProcessor.Web.Configuration.SettingElementCollection.CreateNewElement
  href: ImageProcessor.Web.Configuration.SettingElementCollection.yml
  name: CreateNewElement()
  fullName: ImageProcessor.Web.Configuration.SettingElementCollection.CreateNewElement()
  type: Method
  source:
    remote: *o0
    path: src/ImageProcessor.Web/Configuration/Shared/SettingElementCollection.cs
    startLine: 111
  summary: Creates a new SettingElement configuration element.
  syntax:
    content:
      CSharp: protected override ConfigurationElement CreateNewElement()
    parameters: []
    return:
      id: ConfigurationElement
      type:
        id: System.Configuration.ConfigurationElement
        name: ConfigurationElement
        isExternal: true
      description: A new SettingElement configuration element.
  id: ImageProcessor.Web.Configuration.SettingElementCollection.CreateNewElement
