items:
- uid: ImageProcessor.Web.Configuration.ImageSecuritySection.WhiteListElementCollection
  href: ImageProcessor.Web.Configuration.ImageSecuritySection.WhiteListElementCollection.yml
  name: WhiteListElementCollection
  fullName: ImageProcessor.Web.Configuration.ImageSecuritySection.WhiteListElementCollection
  type: Class
  source:
    remote: &o0
      path: src/ImageProcessor.Web/Configuration/ImageSecuritySection.cs
      branch: V2
      repo: https://github.com/JimBobSquarePants/ImageProcessor.git
      key: 6d1ac546
    path: src/ImageProcessor.Web/Configuration/ImageSecuritySection.cs
    startLine: 253
  summary: Represents a whitelist collection configuration element within the configuration.
  syntax:
    content:
      CSharp: 'public class WhiteListElementCollection : ConfigurationElementCollection, ICollection, IEnumerable'
  inheritance:
  - id: System.Object
    name: object
    isExternal: true
  - id: System.Configuration.ConfigurationElement
    name: ConfigurationElement
    isExternal: true
  - id: System.Configuration.ConfigurationElementCollection
    name: ConfigurationElementCollection
    isExternal: true
  id: ImageProcessor.Web.Configuration.ImageSecuritySection.WhiteListElementCollection
  children:
  - ImageProcessor.Web.Configuration.ImageSecuritySection.WhiteListElementCollection.Item(System.Int32)
  - ImageProcessor.Web.Configuration.ImageSecuritySection.WhiteListElementCollection.CreateNewElement
  - ImageProcessor.Web.Configuration.ImageSecuritySection.WhiteListElementCollection.GetElementKey(System.Configuration.ConfigurationElement)
- uid: ImageProcessor.Web.Configuration.ImageSecuritySection.WhiteListElementCollection.Item(System.Int32)
  href: ImageProcessor.Web.Configuration.ImageSecuritySection.WhiteListElementCollection.yml
  name: this[int]
  fullName: ImageProcessor.Web.Configuration.ImageSecuritySection.WhiteListElementCollection.this[int]
  type: Property
  source:
    remote: *o0
    path: src/ImageProcessor.Web/Configuration/ImageSecuritySection.cs
    startLine: 260
  summary: Gets or sets the whitelist item at the given index.
  syntax:
    content:
      CSharp: public SafeUrl this[int index] { get; set; }
    parameters:
    - id: this[]
      type:
        id: ImageProcessor.Web.Configuration.ImageSecuritySection.SafeUrl
        name: SafeUrl
        href: ImageProcessor.Web.Configuration.ImageSecuritySection.SafeUrl.yml
  id: ImageProcessor.Web.Configuration.ImageSecuritySection.WhiteListElementCollection.Item(System.Int32)
- uid: ImageProcessor.Web.Configuration.ImageSecuritySection.WhiteListElementCollection.CreateNewElement
  href: ImageProcessor.Web.Configuration.ImageSecuritySection.WhiteListElementCollection.yml
  name: CreateNewElement()
  fullName: ImageProcessor.Web.Configuration.ImageSecuritySection.WhiteListElementCollection.CreateNewElement()
  type: Method
  source:
    remote: *o0
    path: src/ImageProcessor.Web/Configuration/ImageSecuritySection.cs
    startLine: 284
  summary: Creates a new SafeURL configuration element.
  syntax:
    content:
      CSharp: protected override ConfigurationElement CreateNewElement()
    parameters: []
    return:
      id: ConfigurationElement
      type:
        id: System.Configuration.ConfigurationElement
        name: ConfigurationElement
        isExternal: true
      description: A new SafeURL configuration element.
  id: ImageProcessor.Web.Configuration.ImageSecuritySection.WhiteListElementCollection.CreateNewElement
- uid: ImageProcessor.Web.Configuration.ImageSecuritySection.WhiteListElementCollection.GetElementKey(System.Configuration.ConfigurationElement)
  href: ImageProcessor.Web.Configuration.ImageSecuritySection.WhiteListElementCollection.yml
  name: GetElementKey(ConfigurationElement)
  fullName: ImageProcessor.Web.Configuration.ImageSecuritySection.WhiteListElementCollection.GetElementKey(System.Configuration.ConfigurationElement)
  type: Method
  source:
    remote: *o0
    path: src/ImageProcessor.Web/Configuration/ImageSecuritySection.cs
    startLine: 294
  summary: Gets the element key for a specified whitelist configuration element.
  syntax:
    content:
      CSharp: protected override object GetElementKey(ConfigurationElement element)
    parameters:
    - id: element
      type:
        id: System.Configuration.ConfigurationElement
        name: ConfigurationElement
        isExternal: true
      description: The [System.Configuration.ConfigurationElement](#) to return the key for.
    return:
      id: Object
      type:
        id: System.Object
        name: object
        isExternal: true
      description: The element key for a specified whitelist configuration element.
  id: ImageProcessor.Web.Configuration.ImageSecuritySection.WhiteListElementCollection.GetElementKey(System.Configuration.ConfigurationElement)
