items:
- uid: ImageProcessor.Web.PostProcessor.ApplicationEvents
  href: ImageProcessor.Web.PostProcessor.ApplicationEvents.yml
  name: ApplicationEvents
  fullName: ImageProcessor.Web.PostProcessor.ApplicationEvents
  type: Class
  source:
    remote: &o0
      path: src/ImageProcessor.Web.PostProcessor/ApplicationEvents.cs
      branch: V2
      repo: https://github.com/JimBobSquarePants/ImageProcessor.git
      key: 6d1ac546
    path: src/ImageProcessor.Web.PostProcessor/ApplicationEvents.cs
    startLine: 24
  summary: >-
    Binds the PostProcessor to process any image requests within the web application.

    Many thanks to Azure Image Optimizer
  syntax:
    content:
      CSharp: public class ApplicationEvents
  inheritance:
  - id: System.Object
    name: object
    isExternal: true
  id: ImageProcessor.Web.PostProcessor.ApplicationEvents
  children:
  - ImageProcessor.Web.PostProcessor.ApplicationEvents.Start
- uid: ImageProcessor.Web.PostProcessor.ApplicationEvents.Start
  href: ImageProcessor.Web.PostProcessor.ApplicationEvents.yml
  name: Start()
  fullName: ImageProcessor.Web.PostProcessor.ApplicationEvents.Start()
  type: Method
  source:
    remote: *o0
    path: src/ImageProcessor.Web.PostProcessor/ApplicationEvents.cs
    startLine: 29
  summary: The initial startup method.
  syntax:
    content:
      CSharp: public static void Start()
    parameters: []
  id: ImageProcessor.Web.PostProcessor.ApplicationEvents.Start
