items:
- uid: ImageProcessor.Web.Configuration.ImageProcessingSection
  href: ImageProcessor.Web.Configuration.ImageProcessingSection.yml
  name: ImageProcessingSection
  fullName: ImageProcessor.Web.Configuration.ImageProcessingSection
  type: Class
  source:
    remote: &o0
      path: src/ImageProcessor.Web/Configuration/ImageProcessingSection.cs
      branch: V2
      repo: https://github.com/JimBobSquarePants/ImageProcessor.git
      key: 6d1ac546
    path: src/ImageProcessor.Web/Configuration/ImageProcessingSection.cs
    startLine: 23
  summary: >-
    Represents an image processing section within a configuration file.

    Nested syntax adapted from
  syntax:
    content:
      CSharp: 'public sealed class ImageProcessingSection : ConfigurationSection'
  inheritance:
  - id: System.Object
    name: object
    isExternal: true
  - id: System.Configuration.ConfigurationElement
    name: ConfigurationElement
    isExternal: true
  - id: System.Configuration.ConfigurationSection
    name: ConfigurationSection
    isExternal: true
  id: ImageProcessor.Web.Configuration.ImageProcessingSection
  children:
  - ImageProcessor.Web.Configuration.ImageProcessingSection.PreserveExifMetaData
  - ImageProcessor.Web.Configuration.ImageProcessingSection.Presets
  - ImageProcessor.Web.Configuration.ImageProcessingSection.Plugins
  - ImageProcessor.Web.Configuration.ImageProcessingSection.AutoLoadPlugins
  - ImageProcessor.Web.Configuration.ImageProcessingSection.GetConfiguration
- uid: ImageProcessor.Web.Configuration.ImageProcessingSection.PreserveExifMetaData
  href: ImageProcessor.Web.Configuration.ImageProcessingSection.yml
  name: PreserveExifMetaData
  fullName: ImageProcessor.Web.Configuration.ImageProcessingSection.PreserveExifMetaData
  type: Property
  source:
    remote: *o0
    path: src/ImageProcessor.Web/Configuration/ImageProcessingSection.cs
    startLine: 28
  summary: Gets or sets a value indicating whether to preserve exif meta data.
  syntax:
    content:
      CSharp: '[ConfigurationProperty("preserveExifMetaData", IsRequired = false, DefaultValue = false)] public bool PreserveExifMetaData { get; set; }'
    parameters:
    - id: PreserveExifMetaData
      type:
        id: System.Boolean
        name: bool
        isExternal: true
  id: ImageProcessor.Web.Configuration.ImageProcessingSection.PreserveExifMetaData
- uid: ImageProcessor.Web.Configuration.ImageProcessingSection.Presets
  href: ImageProcessor.Web.Configuration.ImageProcessingSection.yml
  name: Presets
  fullName: ImageProcessor.Web.Configuration.ImageProcessingSection.Presets
  type: Property
  source:
    remote: *o0
    path: src/ImageProcessor.Web/Configuration/ImageProcessingSection.cs
    startLine: 41
  summary: Gets the [ImageProcessor.Web.Config.ImageProcessingSection.PresetElementCollection](#).
  syntax:
    content:
      CSharp: '[ConfigurationProperty("presets", IsRequired = true)] public PresetElementCollection Presets { get; }'
    parameters:
    - id: Presets
      type:
        id: ImageProcessor.Web.Configuration.ImageProcessingSection.PresetElementCollection
        name: PresetElementCollection
        href: ImageProcessor.Web.Configuration.ImageProcessingSection.PresetElementCollection.yml
  id: ImageProcessor.Web.Configuration.ImageProcessingSection.Presets
- uid: ImageProcessor.Web.Configuration.ImageProcessingSection.Plugins
  href: ImageProcessor.Web.Configuration.ImageProcessingSection.yml
  name: Plugins
  fullName: ImageProcessor.Web.Configuration.ImageProcessingSection.Plugins
  type: Property
  source:
    remote: *o0
    path: src/ImageProcessor.Web/Configuration/ImageProcessingSection.cs
    startLine: 56
  summary: Gets the [ImageProcessor.Web.Config.ImageProcessingSection.PluginElementCollection](#).
  syntax:
    content:
      CSharp: '[ConfigurationProperty("plugins", IsRequired = true)] public PluginElementCollection Plugins { get; }'
    parameters:
    - id: Plugins
      type:
        id: ImageProcessor.Web.Configuration.ImageProcessingSection.PluginElementCollection
        name: PluginElementCollection
        href: ImageProcessor.Web.Configuration.ImageProcessingSection.PluginElementCollection.yml
  id: ImageProcessor.Web.Configuration.ImageProcessingSection.Plugins
- uid: ImageProcessor.Web.Configuration.ImageProcessingSection.AutoLoadPlugins
  href: ImageProcessor.Web.Configuration.ImageProcessingSection.yml
  name: AutoLoadPlugins
  fullName: ImageProcessor.Web.Configuration.ImageProcessingSection.AutoLoadPlugins
  type: Property
  source:
    remote: *o0
    path: src/ImageProcessor.Web/Configuration/ImageProcessingSection.cs
    startLine: 68
  summary: Gets or sets a value indicating whether to auto load plugins.
  syntax:
    content:
      CSharp: public bool AutoLoadPlugins { get; set; }
    parameters:
    - id: AutoLoadPlugins
      type:
        id: System.Boolean
        name: bool
        isExternal: true
  id: ImageProcessor.Web.Configuration.ImageProcessingSection.AutoLoadPlugins
- uid: ImageProcessor.Web.Configuration.ImageProcessingSection.GetConfiguration
  href: ImageProcessor.Web.Configuration.ImageProcessingSection.yml
  name: GetConfiguration()
  fullName: ImageProcessor.Web.Configuration.ImageProcessingSection.GetConfiguration()
  type: Method
  source:
    remote: *o0
    path: src/ImageProcessor.Web/Configuration/ImageProcessingSection.cs
    startLine: 74
  summary: Retrieves the processing configuration section from the current application configuration.
  syntax:
    content:
      CSharp: public static ImageProcessingSection GetConfiguration()
    parameters: []
    return:
      id: ImageProcessingSection
      type:
        id: ImageProcessor.Web.Configuration.ImageProcessingSection
        name: ImageProcessingSection
        href: ImageProcessor.Web.Configuration.ImageProcessingSection.yml
      description: The processing configuration section from the current application configuration.
  id: ImageProcessor.Web.Configuration.ImageProcessingSection.GetConfiguration
