items:
- uid: ImageProcessor.Web.Configuration.ImageSecuritySection.SafeUrl
  href: ImageProcessor.Web.Configuration.ImageSecuritySection.SafeUrl.yml
  name: SafeUrl
  fullName: ImageProcessor.Web.Configuration.ImageSecuritySection.SafeUrl
  type: Class
  source:
    remote: &o0
      path: src/ImageProcessor.Web/Configuration/ImageSecuritySection.cs
      branch: V2
      repo: https://github.com/JimBobSquarePants/ImageProcessor.git
      key: 6d1ac546
    path: src/ImageProcessor.Web/Configuration/ImageSecuritySection.cs
    startLine: 303
  summary: Represents a whitelist configuration element within the configuration.
  syntax:
    content:
      CSharp: 'public class SafeUrl : ConfigurationElement'
  inheritance:
  - id: System.Object
    name: object
    isExternal: true
  - id: System.Configuration.ConfigurationElement
    name: ConfigurationElement
    isExternal: true
  id: ImageProcessor.Web.Configuration.ImageSecuritySection.SafeUrl
  children:
  - ImageProcessor.Web.Configuration.ImageSecuritySection.SafeUrl.Url
- uid: ImageProcessor.Web.Configuration.ImageSecuritySection.SafeUrl.Url
  href: ImageProcessor.Web.Configuration.ImageSecuritySection.SafeUrl.yml
  name: Url
  fullName: ImageProcessor.Web.Configuration.ImageSecuritySection.SafeUrl.Url
  type: Property
  source:
    remote: *o0
    path: src/ImageProcessor.Web/Configuration/ImageSecuritySection.cs
    startLine: 309
  summary: Gets or sets the url of the white listed file.
  syntax:
    content:
      CSharp: '[ConfigurationProperty("url", DefaultValue = "", IsRequired = true)] public Uri Url { get; set; }'
    parameters:
    - id: Url
      type:
        id: System.Uri
        name: Uri
        isExternal: true
  id: ImageProcessor.Web.Configuration.ImageSecuritySection.SafeUrl.Url
