items:
- uid: ImageProcessor.Configuration
  href: ImageProcessor.Configuration.yml
  name: Configuration
  fullName: ImageProcessor.Configuration
  type: Namespace
  source:
    remote:
      path: src/ImageProcessor/Configuration/NativeMethods.cs
      branch: V2
      repo: https://github.com/JimBobSquarePants/ImageProcessor.git
      key: 6d1ac546
    path: src/ImageProcessor/Configuration/NativeMethods.cs
    startLine: 10
  id: ImageProcessor.Configuration
  children:
  - ImageProcessor.Configuration.ImageProcessorBootstrapper
  - ImageProcessor.Configuration.NativeBinaryFactory
references:
- uid: ImageProcessor.Configuration.ImageProcessorBootstrapper
  href: ImageProcessor.Configuration.ImageProcessorBootstrapper.yml
  name: ImageProcessorBootstrapper
  type: Class
  summary: The ImageProcessor bootstrapper containing initialization code for extending ImageProcessor.
- uid: ImageProcessor.Configuration.NativeBinaryFactory
  href: ImageProcessor.Configuration.NativeBinaryFactory.yml
  name: NativeBinaryFactory
  type: Class
  summary: Controls the loading and unloading of any native binaries required by ImageProcessor.
