items:
- uid: ImageProcessor.UnitTests.Configuration
  href: ImageProcessor.UnitTests.Configuration.yml
  name: Configuration
  fullName: ImageProcessor.UnitTests.Configuration
  type: Namespace
  source:
    remote:
      path: src/ImageProcessor.UnitTests/Configuration/ImageProcessorBootstrapperTests.cs
      branch: V2
      repo: https://github.com/JimBobSquarePants/ImageProcessor.git
      key: 6d1ac546
    path: src/ImageProcessor.UnitTests/Configuration/ImageProcessorBootstrapperTests.cs
    startLine: 10
  id: ImageProcessor.UnitTests.Configuration
  children:
  - ImageProcessor.UnitTests.Configuration.ImageProcessorBootstrapperTests
references:
- uid: ImageProcessor.UnitTests.Configuration.ImageProcessorBootstrapperTests
  href: ImageProcessor.UnitTests.Configuration.ImageProcessorBootstrapperTests.yml
  name: ImageProcessorBootstrapperTests
  type: Class
  summary: Test harness for the ImageProcessor bootstrapper tests
