items:
- uid: ImageProcessor.Web.Configuration.ImageSecuritySection.CORSOriginElement
  href: ImageProcessor.Web.Configuration.ImageSecuritySection.CORSOriginElement.yml
  name: CORSOriginElement
  fullName: ImageProcessor.Web.Configuration.ImageSecuritySection.CORSOriginElement
  type: Class
  source:
    remote: &o0
      path: src/ImageProcessor.Web/Configuration/ImageSecuritySection.cs
      branch: V2
      repo: https://github.com/JimBobSquarePants/ImageProcessor.git
      key: 6d1ac546
    path: src/ImageProcessor.Web/Configuration/ImageSecuritySection.cs
    startLine: 232
  summary: Represents a CORSOriginsElement configuration element within the configuration.
  syntax:
    content:
      CSharp: 'public class CORSOriginElement : ConfigurationElement'
  inheritance:
  - id: System.Object
    name: object
    isExternal: true
  - id: System.Configuration.ConfigurationElement
    name: ConfigurationElement
    isExternal: true
  id: ImageProcessor.Web.Configuration.ImageSecuritySection.CORSOriginElement
  children:
  - ImageProcessor.Web.Configuration.ImageSecuritySection.CORSOriginElement.WhiteList
- uid: ImageProcessor.Web.Configuration.ImageSecuritySection.CORSOriginElement.WhiteList
  href: ImageProcessor.Web.Configuration.ImageSecuritySection.CORSOriginElement.yml
  name: WhiteList
  fullName: ImageProcessor.Web.Configuration.ImageSecuritySection.CORSOriginElement.WhiteList
  type: Property
  source:
    remote: *o0
    path: src/ImageProcessor.Web/Configuration/ImageSecuritySection.cs
    startLine: 240
  summary: Gets the [ImageProcessor.Web.Config.ImageSecuritySection.WhiteListElementCollection](#).
  syntax:
    content:
      CSharp: '[ConfigurationProperty("whitelist", IsRequired = false)] public WhiteListElementCollection WhiteList { get; }'
    parameters:
    - id: WhiteList
      type:
        id: ImageProcessor.Web.Configuration.ImageSecuritySection.WhiteListElementCollection
        name: WhiteListElementCollection
        href: ImageProcessor.Web.Configuration.ImageSecuritySection.WhiteListElementCollection.yml
  id: ImageProcessor.Web.Configuration.ImageSecuritySection.CORSOriginElement.WhiteList
