items:
- uid: ImageProcessor.Web.Configuration.SettingElement
  href: ImageProcessor.Web.Configuration.SettingElement.yml
  name: SettingElement
  fullName: ImageProcessor.Web.Configuration.SettingElement
  type: Class
  source:
    remote: &o0
      path: src/ImageProcessor.Web/Configuration/Shared/SettingElement.cs
      branch: V2
      repo: https://github.com/JimBobSquarePants/ImageProcessor.git
      key: 6d1ac546
    path: src/ImageProcessor.Web/Configuration/Shared/SettingElement.cs
    startLine: 17
  summary: Represents a SettingElement configuration element within the configuration.
  syntax:
    content:
      CSharp: 'public class SettingElement : ConfigurationElement'
  inheritance:
  - id: System.Object
    name: object
    isExternal: true
  - id: System.Configuration.ConfigurationElement
    name: ConfigurationElement
    isExternal: true
  id: ImageProcessor.Web.Configuration.SettingElement
  children:
  - ImageProcessor.Web.Configuration.SettingElement.Key
  - ImageProcessor.Web.Configuration.SettingElement.Value
- uid: ImageProcessor.Web.Configuration.SettingElement.Key
  href: ImageProcessor.Web.Configuration.SettingElement.yml
  name: Key
  fullName: ImageProcessor.Web.Configuration.SettingElement.Key
  type: Property
  source:
    remote: *o0
    path: src/ImageProcessor.Web/Configuration/Shared/SettingElement.cs
    startLine: 23
  summary: Gets or sets the key of the plugin setting.
  syntax:
    content:
      CSharp: '[ConfigurationProperty("key", IsRequired = true, IsKey = true)] public string Key { get; set; }'
    parameters:
    - id: Key
      type:
        id: System.String
        name: string
        isExternal: true
  id: ImageProcessor.Web.Configuration.SettingElement.Key
- uid: ImageProcessor.Web.Configuration.SettingElement.Value
  href: ImageProcessor.Web.Configuration.SettingElement.yml
  name: Value
  fullName: ImageProcessor.Web.Configuration.SettingElement.Value
  type: Property
  source:
    remote: *o0
    path: src/ImageProcessor.Web/Configuration/Shared/SettingElement.cs
    startLine: 41
  summary: Gets or sets the value of the plugin setting.
  syntax:
    content:
      CSharp: '[ConfigurationProperty("value", IsRequired = true)] public string Value { get; set; }'
    parameters:
    - id: Value
      type:
        id: System.String
        name: string
        isExternal: true
  id: ImageProcessor.Web.Configuration.SettingElement.Value
