items:
- uid: ImageProcessor.Web.Configuration.ImageProcessingSection.PresetElementCollection
  href: ImageProcessor.Web.Configuration.ImageProcessingSection.PresetElementCollection.yml
  name: PresetElementCollection
  fullName: ImageProcessor.Web.Configuration.ImageProcessingSection.PresetElementCollection
  type: Class
  source:
    remote: &o0
      path: src/ImageProcessor.Web/Configuration/ImageProcessingSection.cs
      branch: V2
      repo: https://github.com/JimBobSquarePants/ImageProcessor.git
      key: 6d1ac546
    path: src/ImageProcessor.Web/Configuration/ImageProcessingSection.cs
    startLine: 126
  summary: Represents a PresetElementCollection collection configuration element within the configuration.
  syntax:
    content:
      CSharp: 'public class PresetElementCollection : ConfigurationElementCollection, ICollection, IEnumerable'
  inheritance:
  - id: System.Object
    name: object
    isExternal: true
  - id: System.Configuration.ConfigurationElement
    name: ConfigurationElement
    isExternal: true
  - id: System.Configuration.ConfigurationElementCollection
    name: ConfigurationElementCollection
    isExternal: true
  id: ImageProcessor.Web.Configuration.ImageProcessingSection.PresetElementCollection
  children:
  - ImageProcessor.Web.Configuration.ImageProcessingSection.PresetElementCollection.CollectionType
  - ImageProcessor.Web.Configuration.ImageProcessingSection.PresetElementCollection.ElementName
  - ImageProcessor.Web.Configuration.ImageProcessingSection.PresetElementCollection.Item(System.Int32)
  - ImageProcessor.Web.Configuration.ImageProcessingSection.PresetElementCollection.CreateNewElement
  - ImageProcessor.Web.Configuration.ImageProcessingSection.PresetElementCollection.GetElementKey(System.Configuration.ConfigurationElement)
- uid: ImageProcessor.Web.Configuration.ImageProcessingSection.PresetElementCollection.CollectionType
  href: ImageProcessor.Web.Configuration.ImageProcessingSection.PresetElementCollection.yml
  name: CollectionType
  fullName: ImageProcessor.Web.Configuration.ImageProcessingSection.PresetElementCollection.CollectionType
  type: Property
  source:
    remote: *o0
    path: src/ImageProcessor.Web/Configuration/ImageProcessingSection.cs
    startLine: 134
  summary: Gets the type of the [System.Configuration.ConfigurationElementCollection](#).
  syntax:
    content:
      CSharp: public override ConfigurationElementCollectionType CollectionType { get; }
    parameters:
    - id: CollectionType
      type:
        id: System.Configuration.ConfigurationElementCollectionType
        name: ConfigurationElementCollectionType
        isExternal: true
  id: ImageProcessor.Web.Configuration.ImageProcessingSection.PresetElementCollection.CollectionType
- uid: ImageProcessor.Web.Configuration.ImageProcessingSection.PresetElementCollection.ElementName
  href: ImageProcessor.Web.Configuration.ImageProcessingSection.PresetElementCollection.yml
  name: ElementName
  fullName: ImageProcessor.Web.Configuration.ImageProcessingSection.PresetElementCollection.ElementName
  type: Property
  source:
    remote: *o0
    path: src/ImageProcessor.Web/Configuration/ImageProcessingSection.cs
    startLine: 145
  summary: Gets the name used to identify this collection of elements in the configuration file when overridden in a derived class.
  syntax:
    content:
      CSharp: protected override string ElementName { get; }
    parameters:
    - id: ElementName
      type:
        id: System.String
        name: string
        isExternal: true
  id: ImageProcessor.Web.Configuration.ImageProcessingSection.PresetElementCollection.ElementName
- uid: ImageProcessor.Web.Configuration.ImageProcessingSection.PresetElementCollection.Item(System.Int32)
  href: ImageProcessor.Web.Configuration.ImageProcessingSection.PresetElementCollection.yml
  name: this[int]
  fullName: ImageProcessor.Web.Configuration.ImageProcessingSection.PresetElementCollection.this[int]
  type: Property
  source:
    remote: *o0
    path: src/ImageProcessor.Web/Configuration/ImageProcessingSection.cs
    startLine: 161
  summary: >-
    Gets or sets the [ImageProcessor.Web.Config.ImageProcessingSection.PresetElement](#)

    at the specified index within the collection.
  syntax:
    content:
      CSharp: public PresetElement this[int index] { get; set; }
    parameters:
    - id: this[]
      type:
        id: ImageProcessor.Web.Configuration.ImageProcessingSection.PresetElement
        name: PresetElement
        href: ImageProcessor.Web.Configuration.ImageProcessingSection.PresetElement.yml
  id: ImageProcessor.Web.Configuration.ImageProcessingSection.PresetElementCollection.Item(System.Int32)
- uid: ImageProcessor.Web.Configuration.ImageProcessingSection.PresetElementCollection.CreateNewElement
  href: ImageProcessor.Web.Configuration.ImageProcessingSection.PresetElementCollection.yml
  name: CreateNewElement()
  fullName: ImageProcessor.Web.Configuration.ImageProcessingSection.PresetElementCollection.CreateNewElement()
  type: Method
  source:
    remote: *o0
    path: src/ImageProcessor.Web/Configuration/ImageProcessingSection.cs
    startLine: 185
  summary: Creates a new Preset configuration element.
  syntax:
    content:
      CSharp: protected override ConfigurationElement CreateNewElement()
    parameters: []
    return:
      id: ConfigurationElement
      type:
        id: System.Configuration.ConfigurationElement
        name: ConfigurationElement
        isExternal: true
      description: A new PluginConfig configuration element.
  id: ImageProcessor.Web.Configuration.ImageProcessingSection.PresetElementCollection.CreateNewElement
- uid: ImageProcessor.Web.Configuration.ImageProcessingSection.PresetElementCollection.GetElementKey(System.Configuration.ConfigurationElement)
  href: ImageProcessor.Web.Configuration.ImageProcessingSection.PresetElementCollection.yml
  name: GetElementKey(ConfigurationElement)
  fullName: ImageProcessor.Web.Configuration.ImageProcessingSection.PresetElementCollection.GetElementKey(System.Configuration.ConfigurationElement)
  type: Method
  source:
    remote: *o0
    path: src/ImageProcessor.Web/Configuration/ImageProcessingSection.cs
    startLine: 200
  summary: Gets the element key for a specified PluginElement configuration element.
  syntax:
    content:
      CSharp: protected override object GetElementKey(ConfigurationElement element)
    parameters:
    - id: element
      type:
        id: System.Configuration.ConfigurationElement
        name: ConfigurationElement
        isExternal: true
      description: >-
        The [System.Configuration.ConfigurationElement](#)

        to return the key for.
    return:
      id: Object
      type:
        id: System.Object
        name: object
        isExternal: true
      description: The element key for a specified PluginElement configuration element.
  id: ImageProcessor.Web.Configuration.ImageProcessingSection.PresetElementCollection.GetElementKey(System.Configuration.ConfigurationElement)
