items:
- uid: ImageProcessor.Web.Configuration.ImageProcessingSection.PresetElement
  href: ImageProcessor.Web.Configuration.ImageProcessingSection.PresetElement.yml
  name: PresetElement
  fullName: ImageProcessor.Web.Configuration.ImageProcessingSection.PresetElement
  type: Class
  source:
    remote: &o0
      path: src/ImageProcessor.Web/Configuration/ImageProcessingSection.cs
      branch: V2
      repo: https://github.com/JimBobSquarePants/ImageProcessor.git
      key: 6d1ac546
    path: src/ImageProcessor.Web/Configuration/ImageProcessingSection.cs
    startLine: 96
  summary: Represents a PresetElement configuration element within the configuration.
  syntax:
    content:
      CSharp: 'public class PresetElement : ConfigurationElement'
  inheritance:
  - id: System.Object
    name: object
    isExternal: true
  - id: System.Configuration.ConfigurationElement
    name: ConfigurationElement
    isExternal: true
  id: ImageProcessor.Web.Configuration.ImageProcessingSection.PresetElement
  children:
  - ImageProcessor.Web.Configuration.ImageProcessingSection.PresetElement.Name
  - ImageProcessor.Web.Configuration.ImageProcessingSection.PresetElement.Value
- uid: ImageProcessor.Web.Configuration.ImageProcessingSection.PresetElement.Name
  href: ImageProcessor.Web.Configuration.ImageProcessingSection.PresetElement.yml
  name: Name
  fullName: ImageProcessor.Web.Configuration.ImageProcessingSection.PresetElement.Name
  type: Property
  source:
    remote: *o0
    path: src/ImageProcessor.Web/Configuration/ImageProcessingSection.cs
    startLine: 102
  summary: Gets or sets the name of the preset.
  syntax:
    content:
      CSharp: '[ConfigurationProperty("name", DefaultValue = "", IsRequired = true)] public string Name { get; set; }'
    parameters:
    - id: Name
      type:
        id: System.String
        name: string
        isExternal: true
  id: ImageProcessor.Web.Configuration.ImageProcessingSection.PresetElement.Name
- uid: ImageProcessor.Web.Configuration.ImageProcessingSection.PresetElement.Value
  href: ImageProcessor.Web.Configuration.ImageProcessingSection.PresetElement.yml
  name: Value
  fullName: ImageProcessor.Web.Configuration.ImageProcessingSection.PresetElement.Value
  type: Property
  source:
    remote: *o0
    path: src/ImageProcessor.Web/Configuration/ImageProcessingSection.cs
    startLine: 114
  summary: Gets or sets the value of the preset.
  syntax:
    content:
      CSharp: '[ConfigurationProperty("value", DefaultValue = "", IsRequired = true)] public string Value { get; set; }'
    parameters:
    - id: Value
      type:
        id: System.String
        name: string
        isExternal: true
  id: ImageProcessor.Web.Configuration.ImageProcessingSection.PresetElement.Value
