items:
- uid: ImageProcessor.Web.Configuration.ImageProcessingSection.PluginElement
  href: ImageProcessor.Web.Configuration.ImageProcessingSection.PluginElement.yml
  name: PluginElement
  fullName: ImageProcessor.Web.Configuration.ImageProcessingSection.PluginElement
  type: Class
  source:
    remote: &o0
      path: src/ImageProcessor.Web/Configuration/ImageProcessingSection.cs
      branch: V2
      repo: https://github.com/JimBobSquarePants/ImageProcessor.git
      key: 6d1ac546
    path: src/ImageProcessor.Web/Configuration/ImageProcessingSection.cs
    startLine: 209
  summary: Represents a PluginElement configuration element within the configuration.
  syntax:
    content:
      CSharp: 'public class PluginElement : ConfigurationElement'
  inheritance:
  - id: System.Object
    name: object
    isExternal: true
  - id: System.Configuration.ConfigurationElement
    name: ConfigurationElement
    isExternal: true
  id: ImageProcessor.Web.Configuration.ImageProcessingSection.PluginElement
  children:
  - ImageProcessor.Web.Configuration.ImageProcessingSection.PluginElement.Name
  - ImageProcessor.Web.Configuration.ImageProcessingSection.PluginElement.Type
  - ImageProcessor.Web.Configuration.ImageProcessingSection.PluginElement.Settings
- uid: ImageProcessor.Web.Configuration.ImageProcessingSection.PluginElement.Name
  href: ImageProcessor.Web.Configuration.ImageProcessingSection.PluginElement.yml
  name: Name
  fullName: ImageProcessor.Web.Configuration.ImageProcessingSection.PluginElement.Name
  type: Property
  source:
    remote: *o0
    path: src/ImageProcessor.Web/Configuration/ImageProcessingSection.cs
    startLine: 215
  summary: Gets or sets the name of the plugin file.
  syntax:
    content:
      CSharp: '[ConfigurationProperty("name", DefaultValue = "", IsRequired = true)] public string Name { get; set; }'
    parameters:
    - id: Name
      type:
        id: System.String
        name: string
        isExternal: true
  id: ImageProcessor.Web.Configuration.ImageProcessingSection.PluginElement.Name
- uid: ImageProcessor.Web.Configuration.ImageProcessingSection.PluginElement.Type
  href: ImageProcessor.Web.Configuration.ImageProcessingSection.PluginElement.yml
  name: Type
  fullName: ImageProcessor.Web.Configuration.ImageProcessingSection.PluginElement.Type
  type: Property
  source:
    remote: *o0
    path: src/ImageProcessor.Web/Configuration/ImageProcessingSection.cs
    startLine: 227
  summary: Gets or sets the type of the plugin file.
  syntax:
    content:
      CSharp: '[ConfigurationProperty("type", DefaultValue = "", IsRequired = true)] public string Type { get; set; }'
    parameters:
    - id: Type
      type:
        id: System.String
        name: string
        isExternal: true
  id: ImageProcessor.Web.Configuration.ImageProcessingSection.PluginElement.Type
- uid: ImageProcessor.Web.Configuration.ImageProcessingSection.PluginElement.Settings
  href: ImageProcessor.Web.Configuration.ImageProcessingSection.PluginElement.yml
  name: Settings
  fullName: ImageProcessor.Web.Configuration.ImageProcessingSection.PluginElement.Settings
  type: Property
  source:
    remote: *o0
    path: src/ImageProcessor.Web/Configuration/ImageProcessingSection.cs
    startLine: 241
  summary: Gets the [ImageProcessor.Web.Config.ImageProcessingSection.SettingElementCollection](#).
  syntax:
    content:
      CSharp: '[ConfigurationProperty("settings", IsRequired = false)] public SettingElementCollection Settings { get; }'
    parameters:
    - id: Settings
      type:
        id: ImageProcessor.Web.Configuration.SettingElementCollection
        name: SettingElementCollection
        href: ImageProcessor.Web.Configuration.SettingElementCollection.yml
  id: ImageProcessor.Web.Configuration.ImageProcessingSection.PluginElement.Settings
