items:
- uid: ImageProcessor.Web.Configuration.ImageProcessingSection.PluginElementCollection
  href: ImageProcessor.Web.Configuration.ImageProcessingSection.PluginElementCollection.yml
  name: PluginElementCollection
  fullName: ImageProcessor.Web.Configuration.ImageProcessingSection.PluginElementCollection
  type: Class
  source:
    remote: &o0
      path: src/ImageProcessor.Web/Configuration/ImageProcessingSection.cs
      branch: V2
      repo: https://github.com/JimBobSquarePants/ImageProcessor.git
      key: 6d1ac546
    path: src/ImageProcessor.Web/Configuration/ImageProcessingSection.cs
    startLine: 254
  summary: Represents a PluginElementCollection collection configuration element within the configuration.
  syntax:
    content:
      CSharp: 'public class PluginElementCollection : ConfigurationElementCollection, ICollection, IEnumerable'
  inheritance:
  - id: System.Object
    name: object
    isExternal: true
  - id: System.Configuration.ConfigurationElement
    name: ConfigurationElement
    isExternal: true
  - id: System.Configuration.ConfigurationElementCollection
    name: ConfigurationElementCollection
    isExternal: true
  id: ImageProcessor.Web.Configuration.ImageProcessingSection.PluginElementCollection
  children:
  - ImageProcessor.Web.Configuration.ImageProcessingSection.PluginElementCollection.CollectionType
  - ImageProcessor.Web.Configuration.ImageProcessingSection.PluginElementCollection.ElementName
  - ImageProcessor.Web.Configuration.ImageProcessingSection.PluginElementCollection.Item(System.Int32)
  - ImageProcessor.Web.Configuration.ImageProcessingSection.PluginElementCollection.CreateNewElement
  - ImageProcessor.Web.Configuration.ImageProcessingSection.PluginElementCollection.GetElementKey(System.Configuration.ConfigurationElement)
- uid: ImageProcessor.Web.Configuration.ImageProcessingSection.PluginElementCollection.CollectionType
  href: ImageProcessor.Web.Configuration.ImageProcessingSection.PluginElementCollection.yml
  name: CollectionType
  fullName: ImageProcessor.Web.Configuration.ImageProcessingSection.PluginElementCollection.CollectionType
  type: Property
  source:
    remote: *o0
    path: src/ImageProcessor.Web/Configuration/ImageProcessingSection.cs
    startLine: 262
  summary: Gets the type of the [System.Configuration.ConfigurationElementCollection](#).
  syntax:
    content:
      CSharp: public override ConfigurationElementCollectionType CollectionType { get; }
    parameters:
    - id: CollectionType
      type:
        id: System.Configuration.ConfigurationElementCollectionType
        name: ConfigurationElementCollectionType
        isExternal: true
  id: ImageProcessor.Web.Configuration.ImageProcessingSection.PluginElementCollection.CollectionType
- uid: ImageProcessor.Web.Configuration.ImageProcessingSection.PluginElementCollection.ElementName
  href: ImageProcessor.Web.Configuration.ImageProcessingSection.PluginElementCollection.yml
  name: ElementName
  fullName: ImageProcessor.Web.Configuration.ImageProcessingSection.PluginElementCollection.ElementName
  type: Property
  source:
    remote: *o0
    path: src/ImageProcessor.Web/Configuration/ImageProcessingSection.cs
    startLine: 273
  summary: Gets the name used to identify this collection of elements in the configuration file when overridden in a derived class.
  syntax:
    content:
      CSharp: protected override string ElementName { get; }
    parameters:
    - id: ElementName
      type:
        id: System.String
        name: string
        isExternal: true
  id: ImageProcessor.Web.Configuration.ImageProcessingSection.PluginElementCollection.ElementName
- uid: ImageProcessor.Web.Configuration.ImageProcessingSection.PluginElementCollection.Item(System.Int32)
  href: ImageProcessor.Web.Configuration.ImageProcessingSection.PluginElementCollection.yml
  name: this[int]
  fullName: ImageProcessor.Web.Configuration.ImageProcessingSection.PluginElementCollection.this[int]
  type: Property
  source:
    remote: *o0
    path: src/ImageProcessor.Web/Configuration/ImageProcessingSection.cs
    startLine: 289
  summary: >-
    Gets or sets the [ImageProcessor.Web.Config.ImageProcessingSection.PluginElement](#)

    at the specified index within the collection.
  syntax:
    content:
      CSharp: public PluginElement this[int index] { get; set; }
    parameters:
    - id: this[]
      type:
        id: ImageProcessor.Web.Configuration.ImageProcessingSection.PluginElement
        name: PluginElement
        href: ImageProcessor.Web.Configuration.ImageProcessingSection.PluginElement.yml
  id: ImageProcessor.Web.Configuration.ImageProcessingSection.PluginElementCollection.Item(System.Int32)
- uid: ImageProcessor.Web.Configuration.ImageProcessingSection.PluginElementCollection.CreateNewElement
  href: ImageProcessor.Web.Configuration.ImageProcessingSection.PluginElementCollection.yml
  name: CreateNewElement()
  fullName: ImageProcessor.Web.Configuration.ImageProcessingSection.PluginElementCollection.CreateNewElement()
  type: Method
  source:
    remote: *o0
    path: src/ImageProcessor.Web/Configuration/ImageProcessingSection.cs
    startLine: 313
  summary: Creates a new Plugin configuration element.
  syntax:
    content:
      CSharp: protected override ConfigurationElement CreateNewElement()
    parameters: []
    return:
      id: ConfigurationElement
      type:
        id: System.Configuration.ConfigurationElement
        name: ConfigurationElement
        isExternal: true
      description: A new Plugin configuration element.
  id: ImageProcessor.Web.Configuration.ImageProcessingSection.PluginElementCollection.CreateNewElement
- uid: ImageProcessor.Web.Configuration.ImageProcessingSection.PluginElementCollection.GetElementKey(System.Configuration.ConfigurationElement)
  href: ImageProcessor.Web.Configuration.ImageProcessingSection.PluginElementCollection.yml
  name: GetElementKey(ConfigurationElement)
  fullName: ImageProcessor.Web.Configuration.ImageProcessingSection.PluginElementCollection.GetElementKey(System.Configuration.ConfigurationElement)
  type: Method
  source:
    remote: *o0
    path: src/ImageProcessor.Web/Configuration/ImageProcessingSection.cs
    startLine: 328
  summary: Gets the element key for a specified PluginElement configuration element.
  syntax:
    content:
      CSharp: protected override object GetElementKey(ConfigurationElement element)
    parameters:
    - id: element
      type:
        id: System.Configuration.ConfigurationElement
        name: ConfigurationElement
        isExternal: true
      description: >-
        The [System.Configuration.ConfigurationElement](#)

        to return the key for.
    return:
      id: Object
      type:
        id: System.Object
        name: object
        isExternal: true
      description: The element key for a specified PluginElement configuration element.
  id: ImageProcessor.Web.Configuration.ImageProcessingSection.PluginElementCollection.GetElementKey(System.Configuration.ConfigurationElement)
