items:
- uid: ImageProcessor.Web.Configuration.ImageProcessorConfiguration
  href: ImageProcessor.Web.Configuration.ImageProcessorConfiguration.yml
  name: ImageProcessorConfiguration
  fullName: ImageProcessor.Web.Configuration.ImageProcessorConfiguration
  type: Class
  source:
    remote: &o0
      path: src/ImageProcessor.Web/Configuration/ImageProcessorConfiguration.cs
      branch: V2
      repo: https://github.com/JimBobSquarePants/ImageProcessor.git
      key: 6d1ac546
    path: src/ImageProcessor.Web/Configuration/ImageProcessorConfiguration.cs
    startLine: 29
  summary: Encapsulates methods to allow the retrieval of ImageProcessor settings.
  syntax:
    content:
      CSharp: public sealed class ImageProcessorConfiguration
  inheritance:
  - id: System.Object
    name: object
    isExternal: true
  id: ImageProcessor.Web.Configuration.ImageProcessorConfiguration
  children:
  - ImageProcessor.Web.Configuration.ImageProcessorConfiguration.Instance
  - ImageProcessor.Web.Configuration.ImageProcessorConfiguration.GraphicsProcessors
  - ImageProcessor.Web.Configuration.ImageProcessorConfiguration.ImageServices
  - ImageProcessor.Web.Configuration.ImageProcessorConfiguration.ImageCache
  - ImageProcessor.Web.Configuration.ImageProcessorConfiguration.ImageCacheMaxDays
  - ImageProcessor.Web.Configuration.ImageProcessorConfiguration.ImageCacheSettings
  - ImageProcessor.Web.Configuration.ImageProcessorConfiguration.PreserveExifMetaData
  - ImageProcessor.Web.Configuration.ImageProcessorConfiguration.GetPresetSettings(System.String)
- uid: ImageProcessor.Web.Configuration.ImageProcessorConfiguration.Instance
  href: ImageProcessor.Web.Configuration.ImageProcessorConfiguration.yml
  name: Instance
  fullName: ImageProcessor.Web.Configuration.ImageProcessorConfiguration.Instance
  type: Property
  source:
    remote: *o0
    path: src/ImageProcessor.Web/Configuration/ImageProcessorConfiguration.cs
    startLine: 77
  summary: Gets the current instance of the [ImageProcessor.Web.Configuration.ImageProcessorConfiguration](api/ImageProcessor.Web.Configuration.ImageProcessorConfiguration.yml) class.
  syntax:
    content:
      CSharp: public static ImageProcessorConfiguration Instance { get; }
    parameters:
    - id: Instance
      type:
        id: ImageProcessor.Web.Configuration.ImageProcessorConfiguration
        name: ImageProcessorConfiguration
        href: ImageProcessor.Web.Configuration.ImageProcessorConfiguration.yml
  id: ImageProcessor.Web.Configuration.ImageProcessorConfiguration.Instance
- uid: ImageProcessor.Web.Configuration.ImageProcessorConfiguration.GraphicsProcessors
  href: ImageProcessor.Web.Configuration.ImageProcessorConfiguration.yml
  name: GraphicsProcessors
  fullName: ImageProcessor.Web.Configuration.ImageProcessorConfiguration.GraphicsProcessors
  type: Property
  source:
    remote: *o0
    path: src/ImageProcessor.Web/Configuration/ImageProcessorConfiguration.cs
    startLine: 88
  summary: Gets the list of available GraphicsProcessors.
  syntax:
    content:
      CSharp: public IList<IWebGraphicsProcessor> GraphicsProcessors { get; }
    parameters:
    - id: GraphicsProcessors
      type:
        id: System.Collections.Generic.IList{ImageProcessor.Web.Processors.IWebGraphicsProcessor}
        name: IList<IWebGraphicsProcessor>
        isExternal: true
  id: ImageProcessor.Web.Configuration.ImageProcessorConfiguration.GraphicsProcessors
- uid: ImageProcessor.Web.Configuration.ImageProcessorConfiguration.ImageServices
  href: ImageProcessor.Web.Configuration.ImageProcessorConfiguration.yml
  name: ImageServices
  fullName: ImageProcessor.Web.Configuration.ImageProcessorConfiguration.ImageServices
  type: Property
  source:
    remote: *o0
    path: src/ImageProcessor.Web/Configuration/ImageProcessorConfiguration.cs
    startLine: 93
  summary: Gets the list of available ImageServices.
  syntax:
    content:
      CSharp: public IList<IImageService> ImageServices { get; }
    parameters:
    - id: ImageServices
      type:
        id: System.Collections.Generic.IList{ImageProcessor.Web.Services.IImageService}
        name: IList<IImageService>
        isExternal: true
  id: ImageProcessor.Web.Configuration.ImageProcessorConfiguration.ImageServices
- uid: ImageProcessor.Web.Configuration.ImageProcessorConfiguration.ImageCache
  href: ImageProcessor.Web.Configuration.ImageProcessorConfiguration.yml
  name: ImageCache
  fullName: ImageProcessor.Web.Configuration.ImageProcessorConfiguration.ImageCache
  type: Property
  source:
    remote: *o0
    path: src/ImageProcessor.Web/Configuration/ImageProcessorConfiguration.cs
    startLine: 98
  summary: Gets the current image cache.
  syntax:
    content:
      CSharp: public Type ImageCache { get; }
    parameters:
    - id: ImageCache
      type:
        id: System.Type
        name: Type
        isExternal: true
  id: ImageProcessor.Web.Configuration.ImageProcessorConfiguration.ImageCache
- uid: ImageProcessor.Web.Configuration.ImageProcessorConfiguration.ImageCacheMaxDays
  href: ImageProcessor.Web.Configuration.ImageProcessorConfiguration.yml
  name: ImageCacheMaxDays
  fullName: ImageProcessor.Web.Configuration.ImageProcessorConfiguration.ImageCacheMaxDays
  type: Property
  source:
    remote: *o0
    path: src/ImageProcessor.Web/Configuration/ImageProcessorConfiguration.cs
    startLine: 103
  summary: Gets the image cache max days.
  syntax:
    content:
      CSharp: public int ImageCacheMaxDays { get; }
    parameters:
    - id: ImageCacheMaxDays
      type:
        id: System.Int32
        name: int
        isExternal: true
  id: ImageProcessor.Web.Configuration.ImageProcessorConfiguration.ImageCacheMaxDays
- uid: ImageProcessor.Web.Configuration.ImageProcessorConfiguration.ImageCacheSettings
  href: ImageProcessor.Web.Configuration.ImageProcessorConfiguration.yml
  name: ImageCacheSettings
  fullName: ImageProcessor.Web.Configuration.ImageProcessorConfiguration.ImageCacheSettings
  type: Property
  source:
    remote: *o0
    path: src/ImageProcessor.Web/Configuration/ImageProcessorConfiguration.cs
    startLine: 108
  summary: Gets the image cache settings.
  syntax:
    content:
      CSharp: public Dictionary<string, string> ImageCacheSettings { get; }
    parameters:
    - id: ImageCacheSettings
      type:
        id: System.Collections.Generic.Dictionary{System.String,System.String}
        name: Dictionary<string, string>
        isExternal: true
  id: ImageProcessor.Web.Configuration.ImageProcessorConfiguration.ImageCacheSettings
- uid: ImageProcessor.Web.Configuration.ImageProcessorConfiguration.PreserveExifMetaData
  href: ImageProcessor.Web.Configuration.ImageProcessorConfiguration.yml
  name: PreserveExifMetaData
  fullName: ImageProcessor.Web.Configuration.ImageProcessorConfiguration.PreserveExifMetaData
  type: Property
  source:
    remote: *o0
    path: src/ImageProcessor.Web/Configuration/ImageProcessorConfiguration.cs
    startLine: 113
  summary: Gets a value indicating whether to preserve exif meta data.
  syntax:
    content:
      CSharp: public bool PreserveExifMetaData { get; }
    parameters:
    - id: PreserveExifMetaData
      type:
        id: System.Boolean
        name: bool
        isExternal: true
  id: ImageProcessor.Web.Configuration.ImageProcessorConfiguration.PreserveExifMetaData
- uid: ImageProcessor.Web.Configuration.ImageProcessorConfiguration.GetPresetSettings(System.String)
  href: ImageProcessor.Web.Configuration.ImageProcessorConfiguration.yml
  name: GetPresetSettings(string)
  fullName: ImageProcessor.Web.Configuration.ImageProcessorConfiguration.GetPresetSettings(string)
  type: Method
  source:
    remote: *o0
    path: src/ImageProcessor.Web/Configuration/ImageProcessorConfiguration.cs
    startLine: 132
  summary: Returns the processing instructions matching the preset defined in the configuration.
  syntax:
    content:
      CSharp: public string GetPresetSettings(string name)
    parameters:
    - id: name
      type:
        id: System.String
        name: string
        isExternal: true
      description: The name of the plugin to get the settings for.
    return:
      id: String
      type:
        id: System.String
        name: string
        isExternal: true
      description: The [Systems.String](#) the processing instructions.
  id: ImageProcessor.Web.Configuration.ImageProcessorConfiguration.GetPresetSettings(System.String)
