items:
- uid: ImageProcessor.Web.Configuration
  href: ImageProcessor.Web.Configuration.yml
  name: Configuration
  fullName: ImageProcessor.Web.Configuration
  type: Namespace
  source:
    remote:
      path: src/ImageProcessor.Web/Configuration/ImageSecuritySection.cs
      branch: V2
      repo: https://github.com/JimBobSquarePants/ImageProcessor.git
      key: 6d1ac546
    path: src/ImageProcessor.Web/Configuration/ImageSecuritySection.cs
    startLine: 10
  id: ImageProcessor.Web.Configuration
  children:
  - ImageProcessor.Web.Configuration.SettingElement
  - ImageProcessor.Web.Configuration.SettingElementCollection
  - ImageProcessor.Web.Configuration.ImageCacheSection
  - ImageProcessor.Web.Configuration.ImageCacheSection.CacheElement
  - ImageProcessor.Web.Configuration.ImageCacheSection.CacheElementCollection
  - ImageProcessor.Web.Configuration.ImageProcessingSection
  - ImageProcessor.Web.Configuration.ImageProcessingSection.PresetElement
  - ImageProcessor.Web.Configuration.ImageProcessingSection.PresetElementCollection
  - ImageProcessor.Web.Configuration.ImageProcessingSection.PluginElement
  - ImageProcessor.Web.Configuration.ImageProcessingSection.PluginElementCollection
  - ImageProcessor.Web.Configuration.ImageProcessorConfiguration
  - ImageProcessor.Web.Configuration.ImageSecuritySection
  - ImageProcessor.Web.Configuration.ImageSecuritySection.ServiceElement
  - ImageProcessor.Web.Configuration.ImageSecuritySection.ServiceElementCollection
  - ImageProcessor.Web.Configuration.ImageSecuritySection.CORSOriginElement
  - ImageProcessor.Web.Configuration.ImageSecuritySection.WhiteListElementCollection
  - ImageProcessor.Web.Configuration.ImageSecuritySection.SafeUrl
references:
- uid: ImageProcessor.Web.Configuration.SettingElement
  href: ImageProcessor.Web.Configuration.SettingElement.yml
  name: SettingElement
  type: Class
  summary: Represents a SettingElement configuration element within the configuration.
- uid: ImageProcessor.Web.Configuration.SettingElementCollection
  href: ImageProcessor.Web.Configuration.SettingElementCollection.yml
  name: SettingElementCollection
  type: Class
  summary: Represents a SettingElementCollection collection configuration element within the configuration.
- uid: ImageProcessor.Web.Configuration.ImageCacheSection
  href: ImageProcessor.Web.Configuration.ImageCacheSection.yml
  name: ImageCacheSection
  type: Class
  summary: Represents an image cache section within a configuration file.
- uid: ImageProcessor.Web.Configuration.ImageCacheSection.CacheElement
  href: ImageProcessor.Web.Configuration.ImageCacheSection.CacheElement.yml
  name: CacheElement
  type: Class
  summary: Represents a CacheElement configuration element within the configuration.
- uid: ImageProcessor.Web.Configuration.ImageCacheSection.CacheElementCollection
  href: ImageProcessor.Web.Configuration.ImageCacheSection.CacheElementCollection.yml
  name: CacheElementCollection
  type: Class
  summary: Represents a collection of [ImageProcessor.Web.Configuration.ImageCacheSection.CacheElement](api/ImageProcessor.Web.Configuration.ImageCacheSection.CacheElement.yml) elements within the configuration.
- uid: ImageProcessor.Web.Configuration.ImageProcessingSection
  href: ImageProcessor.Web.Configuration.ImageProcessingSection.yml
  name: ImageProcessingSection
  type: Class
  summary: >-
    Represents an image processing section within a configuration file.

    Nested syntax adapted from
- uid: ImageProcessor.Web.Configuration.ImageProcessingSection.PresetElement
  href: ImageProcessor.Web.Configuration.ImageProcessingSection.PresetElement.yml
  name: PresetElement
  type: Class
  summary: Represents a PresetElement configuration element within the configuration.
- uid: ImageProcessor.Web.Configuration.ImageProcessingSection.PresetElementCollection
  href: ImageProcessor.Web.Configuration.ImageProcessingSection.PresetElementCollection.yml
  name: PresetElementCollection
  type: Class
  summary: Represents a PresetElementCollection collection configuration element within the configuration.
- uid: ImageProcessor.Web.Configuration.ImageProcessingSection.PluginElement
  href: ImageProcessor.Web.Configuration.ImageProcessingSection.PluginElement.yml
  name: PluginElement
  type: Class
  summary: Represents a PluginElement configuration element within the configuration.
- uid: ImageProcessor.Web.Configuration.ImageProcessingSection.PluginElementCollection
  href: ImageProcessor.Web.Configuration.ImageProcessingSection.PluginElementCollection.yml
  name: PluginElementCollection
  type: Class
  summary: Represents a PluginElementCollection collection configuration element within the configuration.
- uid: ImageProcessor.Web.Configuration.ImageProcessorConfiguration
  href: ImageProcessor.Web.Configuration.ImageProcessorConfiguration.yml
  name: ImageProcessorConfiguration
  type: Class
  summary: Encapsulates methods to allow the retrieval of ImageProcessor settings.
- uid: ImageProcessor.Web.Configuration.ImageSecuritySection
  href: ImageProcessor.Web.Configuration.ImageSecuritySection.yml
  name: ImageSecuritySection
  type: Class
  summary: Represents an image security section within a configuration file.
- uid: ImageProcessor.Web.Configuration.ImageSecuritySection.ServiceElement
  href: ImageProcessor.Web.Configuration.ImageSecuritySection.ServiceElement.yml
  name: ServiceElement
  type: Class
  summary: Represents a ServiceElement configuration element within the configuration.
- uid: ImageProcessor.Web.Configuration.ImageSecuritySection.ServiceElementCollection
  href: ImageProcessor.Web.Configuration.ImageSecuritySection.ServiceElementCollection.yml
  name: ServiceElementCollection
  type: Class
  summary: Represents a collection of [ImageProcessor.Web.Configuration.ImageSecuritySection.ServiceElement](api/ImageProcessor.Web.Configuration.ImageSecuritySection.ServiceElement.yml) elements within the configuration.
- uid: ImageProcessor.Web.Configuration.ImageSecuritySection.CORSOriginElement
  href: ImageProcessor.Web.Configuration.ImageSecuritySection.CORSOriginElement.yml
  name: CORSOriginElement
  type: Class
  summary: Represents a CORSOriginsElement configuration element within the configuration.
- uid: ImageProcessor.Web.Configuration.ImageSecuritySection.WhiteListElementCollection
  href: ImageProcessor.Web.Configuration.ImageSecuritySection.WhiteListElementCollection.yml
  name: WhiteListElementCollection
  type: Class
  summary: Represents a whitelist collection configuration element within the configuration.
- uid: ImageProcessor.Web.Configuration.ImageSecuritySection.SafeUrl
  href: ImageProcessor.Web.Configuration.ImageSecuritySection.SafeUrl.yml
  name: SafeUrl
  type: Class
  summary: Represents a whitelist configuration element within the configuration.
