items:
- uid: ImageProcessor.Web.Configuration.ImageCacheSection.CacheElementCollection
  href: ImageProcessor.Web.Configuration.ImageCacheSection.CacheElementCollection.yml
  name: CacheElementCollection
  fullName: ImageProcessor.Web.Configuration.ImageCacheSection.CacheElementCollection
  type: Class
  source:
    remote: &o0
      path: src/ImageProcessor.Web/Configuration/ImageCacheSection.cs
      branch: V2
      repo: https://github.com/JimBobSquarePants/ImageProcessor.git
      key: 6d1ac546
    path: src/ImageProcessor.Web/Configuration/ImageCacheSection.cs
    startLine: 144
  summary: Represents a collection of [ImageProcessor.Web.Configuration.ImageCacheSection.CacheElement](api/ImageProcessor.Web.Configuration.ImageCacheSection.CacheElement.yml) elements within the configuration.
  syntax:
    content:
      CSharp: 'public class CacheElementCollection : ConfigurationElementCollection, ICollection, IEnumerable'
  inheritance:
  - id: System.Object
    name: object
    isExternal: true
  - id: System.Configuration.ConfigurationElement
    name: ConfigurationElement
    isExternal: true
  - id: System.Configuration.ConfigurationElementCollection
    name: ConfigurationElementCollection
    isExternal: true
  id: ImageProcessor.Web.Configuration.ImageCacheSection.CacheElementCollection
  children:
  - ImageProcessor.Web.Configuration.ImageCacheSection.CacheElementCollection.CollectionType
  - ImageProcessor.Web.Configuration.ImageCacheSection.CacheElementCollection.ElementName
  - ImageProcessor.Web.Configuration.ImageCacheSection.CacheElementCollection.Item(System.Int32)
  - ImageProcessor.Web.Configuration.ImageCacheSection.CacheElementCollection.CreateNewElement
  - ImageProcessor.Web.Configuration.ImageCacheSection.CacheElementCollection.GetElementKey(System.Configuration.ConfigurationElement)
- uid: ImageProcessor.Web.Configuration.ImageCacheSection.CacheElementCollection.CollectionType
  href: ImageProcessor.Web.Configuration.ImageCacheSection.CacheElementCollection.yml
  name: CollectionType
  fullName: ImageProcessor.Web.Configuration.ImageCacheSection.CacheElementCollection.CollectionType
  type: Property
  source:
    remote: *o0
    path: src/ImageProcessor.Web/Configuration/ImageCacheSection.cs
    startLine: 152
  summary: Gets the type of the [System.Configuration.ConfigurationElementCollection](#).
  syntax:
    content:
      CSharp: public override ConfigurationElementCollectionType CollectionType { get; }
    parameters:
    - id: CollectionType
      type:
        id: System.Configuration.ConfigurationElementCollectionType
        name: ConfigurationElementCollectionType
        isExternal: true
  id: ImageProcessor.Web.Configuration.ImageCacheSection.CacheElementCollection.CollectionType
- uid: ImageProcessor.Web.Configuration.ImageCacheSection.CacheElementCollection.ElementName
  href: ImageProcessor.Web.Configuration.ImageCacheSection.CacheElementCollection.yml
  name: ElementName
  fullName: ImageProcessor.Web.Configuration.ImageCacheSection.CacheElementCollection.ElementName
  type: Property
  source:
    remote: *o0
    path: src/ImageProcessor.Web/Configuration/ImageCacheSection.cs
    startLine: 163
  summary: Gets the name used to identify this collection of elements in the configuration file when overridden in a derived class.
  syntax:
    content:
      CSharp: protected override string ElementName { get; }
    parameters:
    - id: ElementName
      type:
        id: System.String
        name: string
        isExternal: true
  id: ImageProcessor.Web.Configuration.ImageCacheSection.CacheElementCollection.ElementName
- uid: ImageProcessor.Web.Configuration.ImageCacheSection.CacheElementCollection.Item(System.Int32)
  href: ImageProcessor.Web.Configuration.ImageCacheSection.CacheElementCollection.yml
  name: this[int]
  fullName: ImageProcessor.Web.Configuration.ImageCacheSection.CacheElementCollection.this[int]
  type: Property
  source:
    remote: *o0
    path: src/ImageProcessor.Web/Configuration/ImageCacheSection.cs
    startLine: 177
  summary: >-
    Gets or sets the [ImageProcessor.Web.Configuration.ImageCacheSection.CacheElement](api/ImageProcessor.Web.Configuration.ImageCacheSection.CacheElement.yml)

    at the specified index within the collection.
  syntax:
    content:
      CSharp: public CacheElement this[int index] { get; set; }
    parameters:
    - id: this[]
      type:
        id: ImageProcessor.Web.Configuration.ImageCacheSection.CacheElement
        name: CacheElement
        href: ImageProcessor.Web.Configuration.ImageCacheSection.CacheElement.yml
  id: ImageProcessor.Web.Configuration.ImageCacheSection.CacheElementCollection.Item(System.Int32)
- uid: ImageProcessor.Web.Configuration.ImageCacheSection.CacheElementCollection.CreateNewElement
  href: ImageProcessor.Web.Configuration.ImageCacheSection.CacheElementCollection.yml
  name: CreateNewElement()
  fullName: ImageProcessor.Web.Configuration.ImageCacheSection.CacheElementCollection.CreateNewElement()
  type: Method
  source:
    remote: *o0
    path: src/ImageProcessor.Web/Configuration/ImageCacheSection.cs
    startLine: 201
  summary: When overridden in a derived class, creates a new [System.Configuration.ConfigurationElement](#).
  syntax:
    content:
      CSharp: protected override ConfigurationElement CreateNewElement()
    parameters: []
    return:
      id: ConfigurationElement
      type:
        id: System.Configuration.ConfigurationElement
        name: ConfigurationElement
        isExternal: true
      description: A new [System.Configuration.ConfigurationElement](#).
  id: ImageProcessor.Web.Configuration.ImageCacheSection.CacheElementCollection.CreateNewElement
- uid: ImageProcessor.Web.Configuration.ImageCacheSection.CacheElementCollection.GetElementKey(System.Configuration.ConfigurationElement)
  href: ImageProcessor.Web.Configuration.ImageCacheSection.CacheElementCollection.yml
  name: GetElementKey(ConfigurationElement)
  fullName: ImageProcessor.Web.Configuration.ImageCacheSection.CacheElementCollection.GetElementKey(System.Configuration.ConfigurationElement)
  type: Method
  source:
    remote: *o0
    path: src/ImageProcessor.Web/Configuration/ImageCacheSection.cs
    startLine: 213
  summary: Gets the element key for a specified configuration element when overridden in a derived class.
  syntax:
    content:
      CSharp: protected override object GetElementKey(ConfigurationElement element)
    parameters:
    - id: element
      type:
        id: System.Configuration.ConfigurationElement
        name: ConfigurationElement
        isExternal: true
      description: The [System.Configuration.ConfigurationElement](#) to return the key for.
    return:
      id: Object
      type:
        id: System.Object
        name: object
        isExternal: true
      description: An [System.Object](#) that acts as the key for the specified [System.Configuration.ConfigurationElement](#).
  id: ImageProcessor.Web.Configuration.ImageCacheSection.CacheElementCollection.GetElementKey(System.Configuration.ConfigurationElement)
