items:
- uid: ImageProcessor.Web.Configuration.ImageSecuritySection
  href: ImageProcessor.Web.Configuration.ImageSecuritySection.yml
  name: ImageSecuritySection
  fullName: ImageProcessor.Web.Configuration.ImageSecuritySection
  type: Class
  source:
    remote: &o0
      path: src/ImageProcessor.Web/Configuration/ImageSecuritySection.cs
      branch: V2
      repo: https://github.com/JimBobSquarePants/ImageProcessor.git
      key: 6d1ac546
    path: src/ImageProcessor.Web/Configuration/ImageSecuritySection.cs
    startLine: 22
  summary: Represents an image security section within a configuration file.
  syntax:
    content:
      CSharp: 'public sealed class ImageSecuritySection : ConfigurationSection'
  inheritance:
  - id: System.Object
    name: object
    isExternal: true
  - id: System.Configuration.ConfigurationElement
    name: ConfigurationElement
    isExternal: true
  - id: System.Configuration.ConfigurationSection
    name: ConfigurationSection
    isExternal: true
  id: ImageProcessor.Web.Configuration.ImageSecuritySection
  children:
  - ImageProcessor.Web.Configuration.ImageSecuritySection.CORSOrigin
  - ImageProcessor.Web.Configuration.ImageSecuritySection.ImageServices
  - ImageProcessor.Web.Configuration.ImageSecuritySection.AutoLoadServices
  - ImageProcessor.Web.Configuration.ImageSecuritySection.GetConfiguration
- uid: ImageProcessor.Web.Configuration.ImageSecuritySection.CORSOrigin
  href: ImageProcessor.Web.Configuration.ImageSecuritySection.yml
  name: CORSOrigin
  fullName: ImageProcessor.Web.Configuration.ImageSecuritySection.CORSOrigin
  type: Property
  source:
    remote: *o0
    path: src/ImageProcessor.Web/Configuration/ImageSecuritySection.cs
    startLine: 28
  summary: Gets the [ImageProcessor.Web.Configuration.ImageSecuritySection.CORSOriginElement](api/ImageProcessor.Web.Configuration.ImageSecuritySection.CORSOriginElement.yml)
  syntax:
    content:
      CSharp: '[ConfigurationProperty("cors", IsRequired = false)] public CORSOriginElement CORSOrigin { get; }'
    parameters:
    - id: CORSOrigin
      type:
        id: ImageProcessor.Web.Configuration.ImageSecuritySection.CORSOriginElement
        name: CORSOriginElement
        href: ImageProcessor.Web.Configuration.ImageSecuritySection.CORSOriginElement.yml
  id: ImageProcessor.Web.Configuration.ImageSecuritySection.CORSOrigin
- uid: ImageProcessor.Web.Configuration.ImageSecuritySection.ImageServices
  href: ImageProcessor.Web.Configuration.ImageSecuritySection.yml
  name: ImageServices
  fullName: ImageProcessor.Web.Configuration.ImageSecuritySection.ImageServices
  type: Property
  source:
    remote: *o0
    path: src/ImageProcessor.Web/Configuration/ImageSecuritySection.cs
    startLine: 42
  summary: Gets the [ImageProcessor.Web.Configuration.ImageSecuritySection.ServiceElementCollection](api/ImageProcessor.Web.Configuration.ImageSecuritySection.ServiceElementCollection.yml)
  syntax:
    content:
      CSharp: '[ConfigurationProperty("services", IsRequired = true)] public ServiceElementCollection ImageServices { get; }'
    parameters:
    - id: ImageServices
      type:
        id: ImageProcessor.Web.Configuration.ImageSecuritySection.ServiceElementCollection
        name: ServiceElementCollection
        href: ImageProcessor.Web.Configuration.ImageSecuritySection.ServiceElementCollection.yml
  id: ImageProcessor.Web.Configuration.ImageSecuritySection.ImageServices
- uid: ImageProcessor.Web.Configuration.ImageSecuritySection.AutoLoadServices
  href: ImageProcessor.Web.Configuration.ImageSecuritySection.yml
  name: AutoLoadServices
  fullName: ImageProcessor.Web.Configuration.ImageSecuritySection.AutoLoadServices
  type: Property
  source:
    remote: *o0
    path: src/ImageProcessor.Web/Configuration/ImageSecuritySection.cs
    startLine: 55
  summary: Gets or sets a value indicating whether to auto load services.
  syntax:
    content:
      CSharp: public bool AutoLoadServices { get; set; }
    parameters:
    - id: AutoLoadServices
      type:
        id: System.Boolean
        name: bool
        isExternal: true
  id: ImageProcessor.Web.Configuration.ImageSecuritySection.AutoLoadServices
- uid: ImageProcessor.Web.Configuration.ImageSecuritySection.GetConfiguration
  href: ImageProcessor.Web.Configuration.ImageSecuritySection.yml
  name: GetConfiguration()
  fullName: ImageProcessor.Web.Configuration.ImageSecuritySection.GetConfiguration()
  type: Method
  source:
    remote: *o0
    path: src/ImageProcessor.Web/Configuration/ImageSecuritySection.cs
    startLine: 61
  summary: Retrieves the security configuration section from the current application configuration.
  syntax:
    content:
      CSharp: public static ImageSecuritySection GetConfiguration()
    parameters: []
    return:
      id: ImageSecuritySection
      type:
        id: ImageProcessor.Web.Configuration.ImageSecuritySection
        name: ImageSecuritySection
        href: ImageProcessor.Web.Configuration.ImageSecuritySection.yml
      description: The cache configuration section from the current application configuration.
  id: ImageProcessor.Web.Configuration.ImageSecuritySection.GetConfiguration
