items:
- uid: Test_Website_NET45.MvcApplication
  href: Test_Website_NET45.MvcApplication.yml
  name: MvcApplication
  fullName: Test_Website_NET45.MvcApplication
  type: Class
  source:
    remote: &o0
      path: src/TestWebsites/MVC/Global.asax.cs
      branch: V2
      repo: https://github.com/JimBobSquarePants/ImageProcessor.git
      key: 6d1ac546
    path: src/TestWebsites/MVC/Global.asax.cs
    startLine: 19
  syntax:
    content:
      CSharp: 'public class MvcApplication : HttpApplication, IComponent, IDisposable, IHttpAsyncHandler, IHttpHandler, IRequestCompletedNotifier, ISyncContext'
  inheritance:
  - id: System.Object
    name: object
    isExternal: true
  - id: System.Web.HttpApplication
    name: HttpApplication
    isExternal: true
  id: Test_Website_NET45.MvcApplication
  children:
  - Test_Website_NET45.MvcApplication.Application_Start
- uid: Test_Website_NET45.MvcApplication.Application_Start
  href: Test_Website_NET45.MvcApplication.yml
  name: Application_Start()
  fullName: Test_Website_NET45.MvcApplication.Application_Start()
  type: Method
  source:
    remote: *o0
    path: src/TestWebsites/MVC/Global.asax.cs
    startLine: 21
  syntax:
    content:
      CSharp: protected void Application_Start()
    parameters: []
  id: Test_Website_NET45.MvcApplication.Application_Start
