items:
- uid: Test_Website_NET45.FilterConfig
  href: Test_Website_NET45.FilterConfig.yml
  name: FilterConfig
  fullName: Test_Website_NET45.FilterConfig
  type: Class
  source:
    remote: &o0
      path: src/TestWebsites/MVC/App_Start/FilterConfig.cs
      branch: V2
      repo: https://github.com/JimBobSquarePants/ImageProcessor.git
      key: 6d1ac546
    path: src/TestWebsites/MVC/App_Start/FilterConfig.cs
    startLine: 5
  syntax:
    content:
      CSharp: public class FilterConfig
  inheritance:
  - id: System.Object
    name: object
    isExternal: true
  id: Test_Website_NET45.FilterConfig
  children:
  - Test_Website_NET45.FilterConfig.RegisterGlobalFilters(System.Web.Mvc.GlobalFilterCollection)
- uid: Test_Website_NET45.FilterConfig.RegisterGlobalFilters(System.Web.Mvc.GlobalFilterCollection)
  href: Test_Website_NET45.FilterConfig.yml
  name: RegisterGlobalFilters(GlobalFilterCollection)
  fullName: Test_Website_NET45.FilterConfig.RegisterGlobalFilters(System.Web.Mvc.GlobalFilterCollection)
  type: Method
  source:
    remote: *o0
    path: src/TestWebsites/MVC/App_Start/FilterConfig.cs
    startLine: 7
  syntax:
    content:
      CSharp: public static void RegisterGlobalFilters(GlobalFilterCollection filters)
    parameters:
    - id: filters
      type:
        id: System.Web.Mvc.GlobalFilterCollection
        name: GlobalFilterCollection
        isExternal: true
  id: Test_Website_NET45.FilterConfig.RegisterGlobalFilters(System.Web.Mvc.GlobalFilterCollection)
