items:
- uid: Test_Website_NET45.WebApiConfig
  href: Test_Website_NET45.WebApiConfig.yml
  name: WebApiConfig
  fullName: Test_Website_NET45.WebApiConfig
  type: Class
  source:
    remote: &o0
      path: src/TestWebsites/MVC/App_Start/WebApiConfig.cs
      branch: V2
      repo: https://github.com/JimBobSquarePants/ImageProcessor.git
      key: 6d1ac546
    path: src/TestWebsites/MVC/App_Start/WebApiConfig.cs
    startLine: 7
  syntax:
    content:
      CSharp: public class WebApiConfig
  inheritance:
  - id: System.Object
    name: object
    isExternal: true
  id: Test_Website_NET45.WebApiConfig
  children:
  - Test_Website_NET45.WebApiConfig.Register(System.Web.Http.HttpConfiguration)
- uid: Test_Website_NET45.WebApiConfig.Register(System.Web.Http.HttpConfiguration)
  href: Test_Website_NET45.WebApiConfig.yml
  name: Register(HttpConfiguration)
  fullName: Test_Website_NET45.WebApiConfig.Register(System.Web.Http.HttpConfiguration)
  type: Method
  source:
    remote: *o0
    path: src/TestWebsites/MVC/App_Start/WebApiConfig.cs
    startLine: 9
  syntax:
    content:
      CSharp: public static void Register(HttpConfiguration config)
    parameters:
    - id: config
      type:
        id: System.Web.Http.HttpConfiguration
        name: HttpConfiguration
        isExternal: true
  id: Test_Website_NET45.WebApiConfig.Register(System.Web.Http.HttpConfiguration)
