items:
- uid: Test_Website_NET45.RouteConfig
  href: Test_Website_NET45.RouteConfig.yml
  name: RouteConfig
  fullName: Test_Website_NET45.RouteConfig
  type: Class
  source:
    remote: &o0
      path: src/TestWebsites/MVC/App_Start/RouteConfig.cs
      branch: V2
      repo: https://github.com/JimBobSquarePants/ImageProcessor.git
      key: 6d1ac546
    path: src/TestWebsites/MVC/App_Start/RouteConfig.cs
    startLine: 9
  syntax:
    content:
      CSharp: public class RouteConfig
  inheritance:
  - id: System.Object
    name: object
    isExternal: true
  id: Test_Website_NET45.RouteConfig
  children:
  - Test_Website_NET45.RouteConfig.RegisterRoutes(System.Web.Routing.RouteCollection)
- uid: Test_Website_NET45.RouteConfig.RegisterRoutes(System.Web.Routing.RouteCollection)
  href: Test_Website_NET45.RouteConfig.yml
  name: RegisterRoutes(RouteCollection)
  fullName: Test_Website_NET45.RouteConfig.RegisterRoutes(System.Web.Routing.RouteCollection)
  type: Method
  source:
    remote: *o0
    path: src/TestWebsites/MVC/App_Start/RouteConfig.cs
    startLine: 11
  syntax:
    content:
      CSharp: public static void RegisterRoutes(RouteCollection routes)
    parameters:
    - id: routes
      type:
        id: System.Web.Routing.RouteCollection
        name: RouteCollection
        isExternal: true
  id: Test_Website_NET45.RouteConfig.RegisterRoutes(System.Web.Routing.RouteCollection)
