id: System.Security
yaml: api/System.Security.yaml
href: api/System.Security
name:
  CSharp: Security
qualifiedName:
  CSharp: System.Security
type: Namespace
source:
  remote:
    branch: master
    repo: https://github.com/pengbian/roslyn.git
    local: C:/Users/peterbi/Documents/GitHub/roslyn/
    sha1: 2b5d9bbb0a0cd1ec596f1459763458c4c95c8e52
  path: src/Compilers/Core/Portable/InternalUtilities/SuppressUnmanagedCodeSecurityAttribute.cs
  startLine: 2
