id: System.Security
yaml: api/System.Security.yaml
href: api/System.Security
name:
  CSharp: Security
qualifiedName:
  CSharp: System.Security
type: Namespace
source:
  remote:
    branch: master
    repo: https://github.com/dotnet/roslyn.git
    local: D:/Repo/RoslynGit/
    sha1: 6bda666d110ac87a7ad853dbe45e8366d8bb8744
  path: src/Compilers/Core/Portable/InternalUtilities/SuppressUnmanagedCodeSecurityAttribute.cs
  startLine: 2
